// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module func1_execute8 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        tmp_mid_execute_0_address0,
        tmp_mid_execute_0_ce0,
        tmp_mid_execute_0_we0,
        tmp_mid_execute_0_d0,
        tmp_mid_execute_0_q0,
        tmp_mid_execute_1_address0,
        tmp_mid_execute_1_ce0,
        tmp_mid_execute_1_we0,
        tmp_mid_execute_1_d0,
        tmp_mid_execute_1_q0,
        tmp_mid_execute_2_address0,
        tmp_mid_execute_2_ce0,
        tmp_mid_execute_2_we0,
        tmp_mid_execute_2_d0,
        tmp_mid_execute_2_q0,
        tmp_mid_execute_3_address0,
        tmp_mid_execute_3_ce0,
        tmp_mid_execute_3_we0,
        tmp_mid_execute_3_d0,
        tmp_mid_execute_3_q0,
        tmp_mid_execute_4_address0,
        tmp_mid_execute_4_ce0,
        tmp_mid_execute_4_we0,
        tmp_mid_execute_4_d0,
        tmp_mid_execute_4_q0,
        tmp_mid_execute_5_address0,
        tmp_mid_execute_5_ce0,
        tmp_mid_execute_5_we0,
        tmp_mid_execute_5_d0,
        tmp_mid_execute_5_q0,
        tmp_mid_execute_6_address0,
        tmp_mid_execute_6_ce0,
        tmp_mid_execute_6_we0,
        tmp_mid_execute_6_d0,
        tmp_mid_execute_6_q0,
        tmp_mid_execute_7_address0,
        tmp_mid_execute_7_ce0,
        tmp_mid_execute_7_we0,
        tmp_mid_execute_7_d0,
        tmp_mid_execute_7_q0,
        A_0_address0,
        A_0_ce0,
        A_0_q0,
        A_1_address0,
        A_1_ce0,
        A_1_q0,
        B_0_address0,
        B_0_ce0,
        B_0_q0,
        B_1_address0,
        B_1_ce0,
        B_1_q0
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_pp0_stage0 = 6'd2;
parameter    ap_ST_fsm_pp0_stage1 = 6'd4;
parameter    ap_ST_fsm_pp0_stage2 = 6'd8;
parameter    ap_ST_fsm_pp0_stage3 = 6'd16;
parameter    ap_ST_fsm_state20 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] tmp_mid_execute_0_address0;
output   tmp_mid_execute_0_ce0;
output   tmp_mid_execute_0_we0;
output  [31:0] tmp_mid_execute_0_d0;
input  [31:0] tmp_mid_execute_0_q0;
output  [5:0] tmp_mid_execute_1_address0;
output   tmp_mid_execute_1_ce0;
output   tmp_mid_execute_1_we0;
output  [31:0] tmp_mid_execute_1_d0;
input  [31:0] tmp_mid_execute_1_q0;
output  [4:0] tmp_mid_execute_2_address0;
output   tmp_mid_execute_2_ce0;
output   tmp_mid_execute_2_we0;
output  [31:0] tmp_mid_execute_2_d0;
input  [31:0] tmp_mid_execute_2_q0;
output  [4:0] tmp_mid_execute_3_address0;
output   tmp_mid_execute_3_ce0;
output   tmp_mid_execute_3_we0;
output  [31:0] tmp_mid_execute_3_d0;
input  [31:0] tmp_mid_execute_3_q0;
output  [4:0] tmp_mid_execute_4_address0;
output   tmp_mid_execute_4_ce0;
output   tmp_mid_execute_4_we0;
output  [31:0] tmp_mid_execute_4_d0;
input  [31:0] tmp_mid_execute_4_q0;
output  [4:0] tmp_mid_execute_5_address0;
output   tmp_mid_execute_5_ce0;
output   tmp_mid_execute_5_we0;
output  [31:0] tmp_mid_execute_5_d0;
input  [31:0] tmp_mid_execute_5_q0;
output  [4:0] tmp_mid_execute_6_address0;
output   tmp_mid_execute_6_ce0;
output   tmp_mid_execute_6_we0;
output  [31:0] tmp_mid_execute_6_d0;
input  [31:0] tmp_mid_execute_6_q0;
output  [4:0] tmp_mid_execute_7_address0;
output   tmp_mid_execute_7_ce0;
output   tmp_mid_execute_7_we0;
output  [31:0] tmp_mid_execute_7_d0;
input  [31:0] tmp_mid_execute_7_q0;
output  [7:0] A_0_address0;
output   A_0_ce0;
input  [31:0] A_0_q0;
output  [7:0] A_1_address0;
output   A_1_ce0;
input  [31:0] A_1_q0;
output  [7:0] B_0_address0;
output   B_0_ce0;
input  [31:0] B_0_q0;
output  [7:0] B_1_address0;
output   B_1_ce0;
input  [31:0] B_1_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[5:0] tmp_mid_execute_0_address0;
reg tmp_mid_execute_0_ce0;
reg tmp_mid_execute_0_we0;
reg[5:0] tmp_mid_execute_1_address0;
reg tmp_mid_execute_1_ce0;
reg tmp_mid_execute_1_we0;
reg[4:0] tmp_mid_execute_2_address0;
reg tmp_mid_execute_2_ce0;
reg tmp_mid_execute_2_we0;
reg[4:0] tmp_mid_execute_3_address0;
reg tmp_mid_execute_3_ce0;
reg tmp_mid_execute_3_we0;
reg[4:0] tmp_mid_execute_4_address0;
reg tmp_mid_execute_4_ce0;
reg tmp_mid_execute_4_we0;
reg[4:0] tmp_mid_execute_5_address0;
reg tmp_mid_execute_5_ce0;
reg tmp_mid_execute_5_we0;
reg[4:0] tmp_mid_execute_6_address0;
reg tmp_mid_execute_6_ce0;
reg tmp_mid_execute_6_we0;
reg[4:0] tmp_mid_execute_7_address0;
reg tmp_mid_execute_7_ce0;
reg tmp_mid_execute_7_we0;
reg[7:0] A_0_address0;
reg A_0_ce0;
reg A_1_ce0;
reg[7:0] B_0_address0;
reg B_0_ce0;
reg B_1_ce0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [11:0] indvar_flatten3_reg_278;
reg   [4:0] i_reg_289;
reg   [8:0] indvar_flatten_reg_301;
reg   [4:0] j_reg_313;
reg   [4:0] k_reg_324;
reg  signed [31:0] reg_336;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_state7_pp0_stage1_iter1;
wire    ap_block_state11_pp0_stage1_iter2;
wire    ap_block_state15_pp0_stage1_iter3;
wire    ap_block_state19_pp0_stage1_iter4;
wire    ap_block_pp0_stage1_11001;
reg   [0:0] exitcond_flatten3_reg_987;
reg   [0:0] exitcond_flatten3_reg_987_pp0_iter2_reg;
reg   [0:0] tmp_7_reg_1103;
reg   [0:0] tmp_7_reg_1103_pp0_iter1_reg;
wire   [2:0] tmp_8_fu_340_p1;
reg   [2:0] tmp_8_reg_942;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_state10_pp0_stage0_iter2;
wire    ap_block_state14_pp0_stage0_iter3;
wire    ap_block_state18_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
reg   [1:0] newIndex_reg_947;
wire   [0:0] sel_tmp_fu_354_p2;
reg   [0:0] sel_tmp_reg_952;
reg   [0:0] sel_tmp_reg_952_pp0_iter1_reg;
reg   [0:0] sel_tmp_reg_952_pp0_iter2_reg;
reg   [0:0] sel_tmp_reg_952_pp0_iter3_reg;
wire   [0:0] sel_tmp4_fu_366_p2;
reg   [0:0] sel_tmp4_reg_957;
reg   [0:0] sel_tmp4_reg_957_pp0_iter1_reg;
reg   [0:0] sel_tmp4_reg_957_pp0_iter2_reg;
reg   [0:0] sel_tmp4_reg_957_pp0_iter3_reg;
wire   [0:0] sel_tmp8_fu_378_p2;
reg   [0:0] sel_tmp8_reg_962;
reg   [0:0] sel_tmp8_reg_962_pp0_iter1_reg;
reg   [0:0] sel_tmp8_reg_962_pp0_iter2_reg;
reg   [0:0] sel_tmp8_reg_962_pp0_iter3_reg;
wire   [0:0] sel_tmp3_fu_390_p2;
reg   [0:0] sel_tmp3_reg_967;
reg   [0:0] sel_tmp3_reg_967_pp0_iter1_reg;
reg   [0:0] sel_tmp3_reg_967_pp0_iter2_reg;
reg   [0:0] sel_tmp3_reg_967_pp0_iter3_reg;
wire   [0:0] or_cond_fu_396_p2;
reg   [0:0] or_cond_reg_972;
reg   [0:0] or_cond_reg_972_pp0_iter1_reg;
reg   [0:0] or_cond_reg_972_pp0_iter2_reg;
reg   [0:0] or_cond_reg_972_pp0_iter3_reg;
wire   [0:0] or_cond2_fu_408_p2;
reg   [0:0] or_cond2_reg_977;
reg   [0:0] or_cond2_reg_977_pp0_iter1_reg;
reg   [0:0] or_cond2_reg_977_pp0_iter2_reg;
reg   [0:0] or_cond2_reg_977_pp0_iter3_reg;
wire   [0:0] or_cond3_fu_414_p2;
reg   [0:0] or_cond3_reg_982;
reg   [0:0] or_cond3_reg_982_pp0_iter1_reg;
reg   [0:0] or_cond3_reg_982_pp0_iter2_reg;
reg   [0:0] or_cond3_reg_982_pp0_iter3_reg;
wire   [0:0] exitcond_flatten3_fu_420_p2;
reg   [0:0] exitcond_flatten3_reg_987_pp0_iter1_reg;
reg   [0:0] exitcond_flatten3_reg_987_pp0_iter3_reg;
wire   [11:0] indvar_flatten_next3_fu_426_p2;
reg   [11:0] indvar_flatten_next3_reg_991;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] exitcond_flatten_fu_432_p2;
reg   [0:0] exitcond_flatten_reg_996;
reg   [0:0] exitcond_flatten_reg_996_pp0_iter1_reg;
reg   [0:0] exitcond_flatten_reg_996_pp0_iter2_reg;
reg   [0:0] exitcond_flatten_reg_996_pp0_iter3_reg;
wire   [4:0] j_mid_fu_438_p3;
reg   [4:0] j_mid_reg_1007;
wire   [0:0] exitcond_fu_446_p2;
reg   [0:0] exitcond_reg_1013;
wire   [0:0] not_exitcond_flatten_fu_464_p2;
reg   [0:0] not_exitcond_flatten_reg_1018;
reg   [0:0] not_exitcond_flatten_reg_1018_pp0_iter1_reg;
reg   [0:0] not_exitcond_flatten_reg_1018_pp0_iter2_reg;
reg   [0:0] not_exitcond_flatten_reg_1018_pp0_iter3_reg;
wire   [0:0] exitcond_mid_fu_469_p2;
reg   [0:0] exitcond_mid_reg_1028;
reg   [0:0] exitcond_mid_reg_1028_pp0_iter1_reg;
reg   [0:0] exitcond_mid_reg_1028_pp0_iter2_reg;
reg   [0:0] exitcond_mid_reg_1028_pp0_iter3_reg;
wire   [4:0] k_mid2_fu_484_p3;
reg   [4:0] k_mid2_reg_1039;
wire   [4:0] tmp_mid2_fu_492_p3;
reg   [4:0] tmp_mid2_reg_1045;
wire   [2:0] tmp_10_fu_499_p1;
reg   [2:0] tmp_10_reg_1052;
reg   [2:0] tmp_10_reg_1052_pp0_iter1_reg;
reg   [2:0] tmp_10_reg_1052_pp0_iter2_reg;
reg   [2:0] tmp_10_reg_1052_pp0_iter3_reg;
wire   [2:0] arrayNo_trunc_mid2_fu_503_p3;
reg   [2:0] arrayNo_trunc_mid2_reg_1063;
reg   [2:0] arrayNo_trunc_mid2_reg_1063_pp0_iter1_reg;
reg   [2:0] arrayNo_trunc_mid2_reg_1063_pp0_iter2_reg;
reg   [2:0] arrayNo_trunc_mid2_reg_1063_pp0_iter3_reg;
wire   [1:0] newIndex7_mid2_fu_521_p3;
reg   [1:0] newIndex7_mid2_reg_1067;
reg   [1:0] newIndex7_mid2_reg_1067_pp0_iter1_reg;
reg   [1:0] newIndex7_mid2_reg_1067_pp0_iter2_reg;
reg   [3:0] newIndex8_reg_1072;
reg   [3:0] newIndex8_reg_1072_pp0_iter1_reg;
wire   [4:0] tmp_mid2_v_fu_545_p3;
reg   [4:0] tmp_mid2_v_reg_1079;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state4_pp0_stage2_iter0;
wire    ap_block_state8_pp0_stage2_iter1;
wire    ap_block_state12_pp0_stage2_iter2;
wire    ap_block_state16_pp0_stage2_iter3;
wire    ap_block_pp0_stage2_11001;
reg   [4:0] tmp_mid2_v_reg_1079_pp0_iter1_reg;
reg   [4:0] tmp_mid2_v_reg_1079_pp0_iter2_reg;
wire   [8:0] tmp_24_fu_587_p2;
reg   [8:0] tmp_24_reg_1093;
wire   [8:0] indvar_flatten_op_fu_593_p2;
reg   [8:0] indvar_flatten_op_reg_1098;
wire   [0:0] tmp_7_fu_599_p2;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state5_pp0_stage3_iter0;
wire    ap_block_state9_pp0_stage3_iter1;
wire    ap_block_state13_pp0_stage3_iter2;
wire    ap_block_state17_pp0_stage3_iter3;
wire    ap_block_pp0_stage3_11001;
reg   [0:0] tmp_7_reg_1103_pp0_iter2_reg;
reg   [0:0] tmp_7_reg_1103_pp0_iter3_reg;
reg  signed [31:0] B_0_load_reg_1108;
wire   [4:0] k_9_1_fu_609_p2;
reg   [4:0] k_9_1_reg_1123;
wire   [8:0] indvar_flatten_next_fu_614_p3;
reg   [8:0] indvar_flatten_next_reg_1128;
reg  signed [31:0] B_0_load_1_reg_1133;
reg    ap_enable_reg_pp0_iter1;
reg  signed [31:0] B_1_load_reg_1138;
wire   [6:0] tmp_fu_635_p3;
reg   [6:0] tmp_reg_1143;
reg   [6:0] tmp_reg_1143_pp0_iter2_reg;
wire  signed [8:0] tmp_16_fu_653_p2;
reg  signed [8:0] tmp_16_reg_1148;
wire   [8:0] tmp_20_fu_662_p2;
reg   [8:0] tmp_20_reg_1153;
wire  signed [31:0] grp_fu_620_p2;
reg  signed [31:0] tmp1_reg_1163;
wire  signed [31:0] grp_fu_625_p2;
reg  signed [31:0] tmp2_reg_1178;
reg  signed [31:0] A_1_load_reg_1183;
wire  signed [31:0] grp_fu_630_p2;
reg  signed [31:0] tmp3_reg_1188;
wire   [6:0] tmp_18_fu_713_p2;
reg   [6:0] tmp_18_reg_1193;
wire   [6:0] tmp_19_fu_719_p2;
reg   [6:0] tmp_19_reg_1198;
reg   [5:0] tmp_mid_execute_0_a_reg_1203;
reg   [5:0] tmp_mid_execute_1_a_reg_1208;
reg   [4:0] tmp_mid_execute_2_a_reg_1213;
reg   [4:0] tmp_mid_execute_3_a_reg_1218;
reg   [4:0] tmp_mid_execute_4_a_reg_1223;
reg   [4:0] tmp_mid_execute_5_a_reg_1228;
reg   [4:0] tmp_mid_execute_6_a_reg_1233;
reg   [4:0] tmp_mid_execute_7_a_reg_1238;
wire   [31:0] grp_fu_677_p2;
reg   [31:0] tmp_9_reg_1243;
wire   [31:0] grp_fu_682_p2;
reg   [31:0] tmp_3_reg_1248;
wire   [0:0] or_cond2_mid2_fu_855_p3;
reg   [0:0] or_cond2_mid2_reg_1253;
wire   [0:0] or_cond3_mid2_fu_868_p3;
reg   [0:0] or_cond3_mid2_reg_1258;
wire   [31:0] newSel2_fu_891_p3;
reg   [31:0] newSel2_reg_1263;
wire   [31:0] newSel3_fu_899_p3;
reg   [31:0] newSel3_reg_1268;
wire   [31:0] newSel4_fu_907_p3;
reg   [31:0] newSel4_reg_1273;
wire   [31:0] grp_fu_687_p2;
reg   [31:0] tmp_12_1_reg_1278;
wire   [31:0] tmp_13_1_fu_937_p2;
reg   [31:0] tmp_13_1_reg_1283;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg   [11:0] ap_phi_mux_indvar_flatten3_phi_fu_282_p4;
wire    ap_block_pp0_stage0;
reg   [4:0] ap_phi_mux_i_phi_fu_293_p4;
wire    ap_block_pp0_stage2;
reg   [8:0] ap_phi_mux_indvar_flatten_phi_fu_305_p4;
reg   [4:0] ap_phi_mux_j_phi_fu_317_p4;
reg   [4:0] ap_phi_mux_k_phi_fu_328_p4;
wire   [63:0] tmp_mid2_cast_25_fu_555_p1;
wire   [63:0] tmp_64_cast_fu_604_p1;
wire    ap_block_pp0_stage3;
wire  signed [63:0] tmp_56_cast_fu_668_p1;
wire  signed [63:0] tmp_60_cast_fu_672_p1;
wire  signed [63:0] tmp_58_cast_fu_725_p1;
wire   [63:0] tmp_59_cast_fu_730_p1;
wire    ap_block_pp0_stage1;
wire   [0:0] sel_tmp1_fu_384_p2;
wire   [0:0] sel_tmp6_fu_372_p2;
wire   [0:0] sel_tmp2_fu_360_p2;
wire   [0:0] or_cond1_fu_402_p2;
wire   [0:0] tmp_17_fu_479_p2;
wire   [4:0] j_2_fu_474_p2;
wire   [2:0] arrayNo_trunc_mid_fu_452_p3;
wire   [1:0] newIndex_mid1_fu_511_p4;
wire   [1:0] newIndex7_mid_fu_458_p3;
wire   [4:0] i_2_fu_539_p2;
wire   [7:0] tmp_21_fu_559_p3;
wire   [4:0] tmp_22_fu_570_p3;
wire   [8:0] p_shl_cast_fu_566_p1;
wire   [8:0] p_shl7_cast_fu_577_p1;
wire   [8:0] tmp_mid2_cast1_fu_552_p1;
wire   [8:0] tmp_23_fu_581_p2;
wire   [7:0] grp_fu_620_p0;
wire   [7:0] grp_fu_625_p0;
wire   [7:0] grp_fu_630_p0;
wire   [8:0] tmp_15_fu_646_p3;
wire   [8:0] p_shl10_cast_fu_642_p1;
wire   [8:0] newIndex9_cast_fu_659_p1;
wire   [6:0] tmp_mid2_cast_fu_691_p1;
wire   [5:0] tmp_14_fu_699_p3;
wire   [6:0] newIndex7_mid2_cast_fu_710_p1;
wire   [6:0] tmp_s_fu_694_p2;
wire   [6:0] tmp_53_cast_fu_706_p1;
wire   [0:0] sel_tmp_mid1_fu_767_p2;
wire   [0:0] sel_tmp_mid_fu_739_p2;
wire   [0:0] sel_tmp4_mid1_fu_784_p2;
wire   [0:0] sel_tmp4_mid_fu_743_p2;
wire   [0:0] sel_tmp8_mid1_fu_801_p2;
wire   [0:0] sel_tmp8_mid_fu_747_p2;
wire   [0:0] sel_tmp3_mid1_fu_818_p2;
wire   [0:0] sel_tmp3_mid_fu_751_p2;
wire   [0:0] sel_tmp1_mid1_fu_813_p2;
wire   [0:0] or_cond_mid1_fu_830_p2;
wire   [0:0] or_cond_mid_fu_755_p2;
wire   [0:0] sel_tmp6_mid1_fu_796_p2;
wire   [0:0] sel_tmp2_mid1_fu_779_p2;
wire   [0:0] or_cond2_mid1_fu_849_p2;
wire   [0:0] or_cond2_mid_fu_759_p2;
wire   [0:0] or_cond1_mid1_fu_843_p2;
wire   [0:0] or_cond3_mid1_fu_862_p2;
wire   [0:0] or_cond3_mid_fu_763_p2;
wire   [0:0] sel_tmp3_mid2_fu_823_p3;
wire   [0:0] sel_tmp8_mid2_fu_806_p3;
wire   [0:0] sel_tmp4_mid2_fu_789_p3;
wire   [0:0] sel_tmp_mid2_fu_772_p3;
wire   [0:0] or_cond_mid2_fu_836_p3;
wire   [31:0] newSel_fu_875_p3;
wire   [31:0] newSel1_fu_883_p3;
wire   [31:0] newSel5_fu_915_p3;
wire   [31:0] newSel6_fu_920_p3;
wire   [31:0] tmp_4_fu_926_p2;
wire   [31:0] storemerge_fu_931_p3;
wire    ap_CS_fsm_state20;
reg   [5:0] ap_NS_fsm;
wire    ap_block_pp0_stage2_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_507;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

kernel_2mm_wrappebkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kernel_2mm_wrappebkb_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_620_p0),
    .din1(B_0_load_reg_1108),
    .ce(1'b1),
    .dout(grp_fu_620_p2)
);

kernel_2mm_wrappebkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kernel_2mm_wrappebkb_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_625_p0),
    .din1(B_0_load_1_reg_1133),
    .ce(1'b1),
    .dout(grp_fu_625_p2)
);

kernel_2mm_wrappebkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kernel_2mm_wrappebkb_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_630_p0),
    .din1(B_1_load_reg_1138),
    .ce(1'b1),
    .dout(grp_fu_630_p2)
);

kernel_2mm_wrappecud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kernel_2mm_wrappecud_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp1_reg_1163),
    .din1(reg_336),
    .ce(1'b1),
    .dout(grp_fu_677_p2)
);

kernel_2mm_wrappecud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kernel_2mm_wrappecud_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp2_reg_1178),
    .din1(reg_336),
    .ce(1'b1),
    .dout(grp_fu_682_p2)
);

kernel_2mm_wrappecud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kernel_2mm_wrappecud_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp3_reg_1188),
    .din1(A_1_load_reg_1183),
    .ce(1'b1),
    .dout(grp_fu_687_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (exitcond_flatten3_reg_987_pp0_iter1_reg == 1'd0))) begin
        i_reg_289 <= tmp_mid2_v_reg_1079;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_289 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten3_reg_987 == 1'd0))) begin
        indvar_flatten3_reg_278 <= indvar_flatten_next3_reg_991;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten3_reg_278 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten3_reg_987 == 1'd0))) begin
        indvar_flatten_reg_301 <= indvar_flatten_next_reg_1128;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_reg_301 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten3_reg_987 == 1'd0))) begin
        j_reg_313 <= tmp_mid2_reg_1045;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j_reg_313 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten3_reg_987 == 1'd0))) begin
        k_reg_324 <= k_9_1_reg_1123;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        k_reg_324 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten3_reg_987_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        A_1_load_reg_1183 <= A_1_q0;
        tmp3_reg_1188 <= grp_fu_630_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten3_reg_987 == 1'd0))) begin
        B_0_load_1_reg_1133 <= B_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten3_reg_987 == 1'd0))) begin
        B_0_load_reg_1108 <= B_0_q0;
        indvar_flatten_next_reg_1128 <= indvar_flatten_next_fu_614_p3;
        k_9_1_reg_1123 <= k_9_1_fu_609_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten3_reg_987 == 1'd0))) begin
        B_1_load_reg_1138 <= B_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten3_reg_987 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        arrayNo_trunc_mid2_reg_1063 <= arrayNo_trunc_mid2_fu_503_p3;
        exitcond_mid_reg_1028 <= exitcond_mid_fu_469_p2;
        k_mid2_reg_1039 <= k_mid2_fu_484_p3;
        newIndex7_mid2_reg_1067 <= newIndex7_mid2_fu_521_p3;
        newIndex8_reg_1072 <= {{k_mid2_fu_484_p3[4:1]}};
        not_exitcond_flatten_reg_1018 <= not_exitcond_flatten_fu_464_p2;
        tmp_10_reg_1052 <= tmp_10_fu_499_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        arrayNo_trunc_mid2_reg_1063_pp0_iter1_reg <= arrayNo_trunc_mid2_reg_1063;
        arrayNo_trunc_mid2_reg_1063_pp0_iter2_reg <= arrayNo_trunc_mid2_reg_1063_pp0_iter1_reg;
        arrayNo_trunc_mid2_reg_1063_pp0_iter3_reg <= arrayNo_trunc_mid2_reg_1063_pp0_iter2_reg;
        exitcond_mid_reg_1028_pp0_iter1_reg <= exitcond_mid_reg_1028;
        exitcond_mid_reg_1028_pp0_iter2_reg <= exitcond_mid_reg_1028_pp0_iter1_reg;
        exitcond_mid_reg_1028_pp0_iter3_reg <= exitcond_mid_reg_1028_pp0_iter2_reg;
        newIndex7_mid2_reg_1067_pp0_iter1_reg <= newIndex7_mid2_reg_1067;
        newIndex7_mid2_reg_1067_pp0_iter2_reg <= newIndex7_mid2_reg_1067_pp0_iter1_reg;
        newIndex8_reg_1072_pp0_iter1_reg <= newIndex8_reg_1072;
        not_exitcond_flatten_reg_1018_pp0_iter1_reg <= not_exitcond_flatten_reg_1018;
        not_exitcond_flatten_reg_1018_pp0_iter2_reg <= not_exitcond_flatten_reg_1018_pp0_iter1_reg;
        not_exitcond_flatten_reg_1018_pp0_iter3_reg <= not_exitcond_flatten_reg_1018_pp0_iter2_reg;
        tmp_10_reg_1052_pp0_iter1_reg <= tmp_10_reg_1052;
        tmp_10_reg_1052_pp0_iter2_reg <= tmp_10_reg_1052_pp0_iter1_reg;
        tmp_10_reg_1052_pp0_iter3_reg <= tmp_10_reg_1052_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond_flatten3_reg_987 <= exitcond_flatten3_fu_420_p2;
        exitcond_flatten3_reg_987_pp0_iter1_reg <= exitcond_flatten3_reg_987;
        exitcond_flatten3_reg_987_pp0_iter2_reg <= exitcond_flatten3_reg_987_pp0_iter1_reg;
        exitcond_flatten3_reg_987_pp0_iter3_reg <= exitcond_flatten3_reg_987_pp0_iter2_reg;
        exitcond_flatten_reg_996_pp0_iter1_reg <= exitcond_flatten_reg_996;
        exitcond_flatten_reg_996_pp0_iter2_reg <= exitcond_flatten_reg_996_pp0_iter1_reg;
        exitcond_flatten_reg_996_pp0_iter3_reg <= exitcond_flatten_reg_996_pp0_iter2_reg;
        newIndex_reg_947 <= {{ap_phi_mux_j_phi_fu_317_p4[4:3]}};
        or_cond2_reg_977 <= or_cond2_fu_408_p2;
        or_cond2_reg_977_pp0_iter1_reg <= or_cond2_reg_977;
        or_cond2_reg_977_pp0_iter2_reg <= or_cond2_reg_977_pp0_iter1_reg;
        or_cond2_reg_977_pp0_iter3_reg <= or_cond2_reg_977_pp0_iter2_reg;
        or_cond3_reg_982 <= or_cond3_fu_414_p2;
        or_cond3_reg_982_pp0_iter1_reg <= or_cond3_reg_982;
        or_cond3_reg_982_pp0_iter2_reg <= or_cond3_reg_982_pp0_iter1_reg;
        or_cond3_reg_982_pp0_iter3_reg <= or_cond3_reg_982_pp0_iter2_reg;
        or_cond_reg_972 <= or_cond_fu_396_p2;
        or_cond_reg_972_pp0_iter1_reg <= or_cond_reg_972;
        or_cond_reg_972_pp0_iter2_reg <= or_cond_reg_972_pp0_iter1_reg;
        or_cond_reg_972_pp0_iter3_reg <= or_cond_reg_972_pp0_iter2_reg;
        sel_tmp3_reg_967 <= sel_tmp3_fu_390_p2;
        sel_tmp3_reg_967_pp0_iter1_reg <= sel_tmp3_reg_967;
        sel_tmp3_reg_967_pp0_iter2_reg <= sel_tmp3_reg_967_pp0_iter1_reg;
        sel_tmp3_reg_967_pp0_iter3_reg <= sel_tmp3_reg_967_pp0_iter2_reg;
        sel_tmp4_reg_957 <= sel_tmp4_fu_366_p2;
        sel_tmp4_reg_957_pp0_iter1_reg <= sel_tmp4_reg_957;
        sel_tmp4_reg_957_pp0_iter2_reg <= sel_tmp4_reg_957_pp0_iter1_reg;
        sel_tmp4_reg_957_pp0_iter3_reg <= sel_tmp4_reg_957_pp0_iter2_reg;
        sel_tmp8_reg_962 <= sel_tmp8_fu_378_p2;
        sel_tmp8_reg_962_pp0_iter1_reg <= sel_tmp8_reg_962;
        sel_tmp8_reg_962_pp0_iter2_reg <= sel_tmp8_reg_962_pp0_iter1_reg;
        sel_tmp8_reg_962_pp0_iter3_reg <= sel_tmp8_reg_962_pp0_iter2_reg;
        sel_tmp_reg_952 <= sel_tmp_fu_354_p2;
        sel_tmp_reg_952_pp0_iter1_reg <= sel_tmp_reg_952;
        sel_tmp_reg_952_pp0_iter2_reg <= sel_tmp_reg_952_pp0_iter1_reg;
        sel_tmp_reg_952_pp0_iter3_reg <= sel_tmp_reg_952_pp0_iter2_reg;
        tmp_8_reg_942 <= tmp_8_fu_340_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten3_fu_420_p2 == 1'd0))) begin
        exitcond_flatten_reg_996 <= exitcond_flatten_fu_432_p2;
        exitcond_reg_1013 <= exitcond_fu_446_p2;
        j_mid_reg_1007 <= j_mid_fu_438_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_next3_reg_991 <= indvar_flatten_next3_fu_426_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (exitcond_flatten_reg_996 == 1'd0) & (exitcond_flatten3_reg_987 == 1'd0))) begin
        indvar_flatten_op_reg_1098 <= indvar_flatten_op_fu_593_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (tmp_7_reg_1103_pp0_iter2_reg == 1'd0) & (exitcond_flatten3_reg_987_pp0_iter3_reg == 1'd0))) begin
        newSel2_reg_1263 <= newSel2_fu_891_p3;
        newSel3_reg_1268 <= newSel3_fu_899_p3;
        newSel4_reg_1273 <= newSel4_fu_907_p3;
        or_cond2_mid2_reg_1253 <= or_cond2_mid2_fu_855_p3;
        or_cond3_mid2_reg_1258 <= or_cond3_mid2_fu_868_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_7_reg_1103_pp0_iter1_reg == 1'd0) & (exitcond_flatten3_reg_987_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_7_reg_1103_pp0_iter1_reg == 1'd1) & (exitcond_flatten3_reg_987_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        reg_336 <= A_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_7_reg_1103_pp0_iter1_reg == 1'd1) & (exitcond_flatten3_reg_987_pp0_iter1_reg == 1'd0))) begin
        tmp1_reg_1163 <= grp_fu_620_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_7_reg_1103_pp0_iter1_reg == 1'd0) & (exitcond_flatten3_reg_987_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp2_reg_1178 <= grp_fu_625_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (exitcond_flatten3_reg_987_pp0_iter3_reg == 1'd0))) begin
        tmp_12_1_reg_1278 <= grp_fu_687_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten3_reg_987_pp0_iter3_reg == 1'd0))) begin
        tmp_13_1_reg_1283 <= tmp_13_1_fu_937_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (exitcond_flatten3_reg_987_pp0_iter1_reg == 1'd0))) begin
        tmp_16_reg_1148[8 : 2] <= tmp_16_fu_653_p2[8 : 2];
        tmp_20_reg_1153 <= tmp_20_fu_662_p2;
        tmp_reg_1143[6 : 2] <= tmp_fu_635_p3[6 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten3_reg_987_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_18_reg_1193 <= tmp_18_fu_713_p2;
        tmp_19_reg_1198 <= tmp_19_fu_719_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (exitcond_flatten3_reg_987 == 1'd0))) begin
        tmp_24_reg_1093 <= tmp_24_fu_587_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (tmp_7_reg_1103_pp0_iter2_reg == 1'd0) & (exitcond_flatten3_reg_987_pp0_iter3_reg == 1'd0))) begin
        tmp_3_reg_1248 <= grp_fu_682_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (exitcond_flatten3_reg_987 == 1'd0))) begin
        tmp_7_reg_1103 <= tmp_7_fu_599_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        tmp_7_reg_1103_pp0_iter1_reg <= tmp_7_reg_1103;
        tmp_7_reg_1103_pp0_iter2_reg <= tmp_7_reg_1103_pp0_iter1_reg;
        tmp_7_reg_1103_pp0_iter3_reg <= tmp_7_reg_1103_pp0_iter2_reg;
        tmp_reg_1143_pp0_iter2_reg[6 : 2] <= tmp_reg_1143[6 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (tmp_7_reg_1103_pp0_iter2_reg == 1'd1) & (exitcond_flatten3_reg_987_pp0_iter3_reg == 1'd0))) begin
        tmp_9_reg_1243 <= grp_fu_677_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten3_reg_987 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_mid2_reg_1045 <= tmp_mid2_fu_492_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten3_reg_987 == 1'd0))) begin
        tmp_mid2_v_reg_1079 <= tmp_mid2_v_fu_545_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_mid2_v_reg_1079_pp0_iter1_reg <= tmp_mid2_v_reg_1079;
        tmp_mid2_v_reg_1079_pp0_iter2_reg <= tmp_mid2_v_reg_1079_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (exitcond_flatten3_reg_987_pp0_iter3_reg == 1'd0))) begin
        tmp_mid_execute_0_a_reg_1203 <= tmp_58_cast_fu_725_p1;
        tmp_mid_execute_1_a_reg_1208 <= tmp_58_cast_fu_725_p1;
        tmp_mid_execute_2_a_reg_1213 <= tmp_59_cast_fu_730_p1;
        tmp_mid_execute_3_a_reg_1218 <= tmp_59_cast_fu_730_p1;
        tmp_mid_execute_4_a_reg_1223 <= tmp_59_cast_fu_730_p1;
        tmp_mid_execute_5_a_reg_1228 <= tmp_59_cast_fu_730_p1;
        tmp_mid_execute_6_a_reg_1233 <= tmp_59_cast_fu_730_p1;
        tmp_mid_execute_7_a_reg_1238 <= tmp_59_cast_fu_730_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_507)) begin
        if ((tmp_7_reg_1103_pp0_iter1_reg == 1'd0)) begin
            A_0_address0 = tmp_60_cast_fu_672_p1;
        end else if ((tmp_7_reg_1103_pp0_iter1_reg == 1'd1)) begin
            A_0_address0 = tmp_56_cast_fu_668_p1;
        end else begin
            A_0_address0 = 'bx;
        end
    end else begin
        A_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_flatten3_reg_987_pp0_iter1_reg == 1'd0) & (tmp_7_reg_1103_pp0_iter1_reg == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_7_reg_1103_pp0_iter1_reg == 1'd1) & (exitcond_flatten3_reg_987_pp0_iter1_reg == 1'd0)))) begin
        A_0_ce0 = 1'b1;
    end else begin
        A_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        A_1_ce0 = 1'b1;
    end else begin
        A_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            B_0_address0 = tmp_64_cast_fu_604_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            B_0_address0 = tmp_mid2_cast_25_fu_555_p1;
        end else begin
            B_0_address0 = 'bx;
        end
    end else begin
        B_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
        B_0_ce0 = 1'b1;
    end else begin
        B_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        B_1_ce0 = 1'b1;
    end else begin
        B_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((exitcond_flatten3_fu_420_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (exitcond_flatten3_reg_987_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_i_phi_fu_293_p4 = tmp_mid2_v_reg_1079;
    end else begin
        ap_phi_mux_i_phi_fu_293_p4 = i_reg_289;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten3_reg_987 == 1'd0))) begin
        ap_phi_mux_indvar_flatten3_phi_fu_282_p4 = indvar_flatten_next3_reg_991;
    end else begin
        ap_phi_mux_indvar_flatten3_phi_fu_282_p4 = indvar_flatten3_reg_278;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten3_reg_987 == 1'd0))) begin
        ap_phi_mux_indvar_flatten_phi_fu_305_p4 = indvar_flatten_next_reg_1128;
    end else begin
        ap_phi_mux_indvar_flatten_phi_fu_305_p4 = indvar_flatten_reg_301;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten3_reg_987 == 1'd0))) begin
        ap_phi_mux_j_phi_fu_317_p4 = tmp_mid2_reg_1045;
    end else begin
        ap_phi_mux_j_phi_fu_317_p4 = j_reg_313;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten3_reg_987 == 1'd0))) begin
        ap_phi_mux_k_phi_fu_328_p4 = k_9_1_reg_1123;
    end else begin
        ap_phi_mux_k_phi_fu_328_p4 = k_reg_324;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_mid_execute_0_address0 = tmp_mid_execute_0_a_reg_1203;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_mid_execute_0_address0 = tmp_58_cast_fu_725_p1;
    end else begin
        tmp_mid_execute_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        tmp_mid_execute_0_ce0 = 1'b1;
    end else begin
        tmp_mid_execute_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((arrayNo_trunc_mid2_reg_1063_pp0_iter3_reg == 3'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_mid_execute_0_we0 = 1'b1;
    end else begin
        tmp_mid_execute_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_mid_execute_1_address0 = tmp_mid_execute_1_a_reg_1208;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_mid_execute_1_address0 = tmp_58_cast_fu_725_p1;
    end else begin
        tmp_mid_execute_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        tmp_mid_execute_1_ce0 = 1'b1;
    end else begin
        tmp_mid_execute_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((arrayNo_trunc_mid2_reg_1063_pp0_iter3_reg == 3'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_mid_execute_1_we0 = 1'b1;
    end else begin
        tmp_mid_execute_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_mid_execute_2_address0 = tmp_mid_execute_2_a_reg_1213;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_mid_execute_2_address0 = tmp_59_cast_fu_730_p1;
    end else begin
        tmp_mid_execute_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        tmp_mid_execute_2_ce0 = 1'b1;
    end else begin
        tmp_mid_execute_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((arrayNo_trunc_mid2_reg_1063_pp0_iter3_reg == 3'd2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_mid_execute_2_we0 = 1'b1;
    end else begin
        tmp_mid_execute_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_mid_execute_3_address0 = tmp_mid_execute_3_a_reg_1218;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_mid_execute_3_address0 = tmp_59_cast_fu_730_p1;
    end else begin
        tmp_mid_execute_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        tmp_mid_execute_3_ce0 = 1'b1;
    end else begin
        tmp_mid_execute_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((arrayNo_trunc_mid2_reg_1063_pp0_iter3_reg == 3'd3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_mid_execute_3_we0 = 1'b1;
    end else begin
        tmp_mid_execute_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_mid_execute_4_address0 = tmp_mid_execute_4_a_reg_1223;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_mid_execute_4_address0 = tmp_59_cast_fu_730_p1;
    end else begin
        tmp_mid_execute_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        tmp_mid_execute_4_ce0 = 1'b1;
    end else begin
        tmp_mid_execute_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((arrayNo_trunc_mid2_reg_1063_pp0_iter3_reg == 3'd4) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_mid_execute_4_we0 = 1'b1;
    end else begin
        tmp_mid_execute_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_mid_execute_5_address0 = tmp_mid_execute_5_a_reg_1228;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_mid_execute_5_address0 = tmp_59_cast_fu_730_p1;
    end else begin
        tmp_mid_execute_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        tmp_mid_execute_5_ce0 = 1'b1;
    end else begin
        tmp_mid_execute_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((arrayNo_trunc_mid2_reg_1063_pp0_iter3_reg == 3'd5) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_mid_execute_5_we0 = 1'b1;
    end else begin
        tmp_mid_execute_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_mid_execute_6_address0 = tmp_mid_execute_6_a_reg_1233;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_mid_execute_6_address0 = tmp_59_cast_fu_730_p1;
    end else begin
        tmp_mid_execute_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        tmp_mid_execute_6_ce0 = 1'b1;
    end else begin
        tmp_mid_execute_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((arrayNo_trunc_mid2_reg_1063_pp0_iter3_reg == 3'd6) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_mid_execute_6_we0 = 1'b1;
    end else begin
        tmp_mid_execute_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_mid_execute_7_address0 = tmp_mid_execute_7_a_reg_1238;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_mid_execute_7_address0 = tmp_59_cast_fu_730_p1;
    end else begin
        tmp_mid_execute_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        tmp_mid_execute_7_ce0 = 1'b1;
    end else begin
        tmp_mid_execute_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((arrayNo_trunc_mid2_reg_1063_pp0_iter3_reg == 3'd7) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_mid_execute_7_we0 = 1'b1;
    end else begin
        tmp_mid_execute_7_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten3_fu_420_p2 == 1'd1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten3_fu_420_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((~((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else if (((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_1_address0 = tmp_60_cast_fu_672_p1;

assign B_1_address0 = tmp_64_cast_fu_604_p1;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_507 = ((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (exitcond_flatten3_reg_987_pp0_iter1_reg == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign arrayNo_trunc_mid2_fu_503_p3 = ((exitcond_mid_fu_469_p2[0:0] === 1'b1) ? tmp_10_fu_499_p1 : arrayNo_trunc_mid_fu_452_p3);

assign arrayNo_trunc_mid_fu_452_p3 = ((exitcond_flatten_reg_996[0:0] === 1'b1) ? 3'd0 : tmp_8_reg_942);

assign exitcond_flatten3_fu_420_p2 = ((ap_phi_mux_indvar_flatten3_phi_fu_282_p4 == 12'd3456) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_432_p2 = ((ap_phi_mux_indvar_flatten_phi_fu_305_p4 == 9'd216) ? 1'b1 : 1'b0);

assign exitcond_fu_446_p2 = ((ap_phi_mux_k_phi_fu_328_p4 == 5'd24) ? 1'b1 : 1'b0);

assign exitcond_mid_fu_469_p2 = (not_exitcond_flatten_fu_464_p2 & exitcond_reg_1013);

assign grp_fu_620_p0 = 32'd123;

assign grp_fu_625_p0 = 32'd123;

assign grp_fu_630_p0 = 32'd123;

assign i_2_fu_539_p2 = (5'd1 + ap_phi_mux_i_phi_fu_293_p4);

assign indvar_flatten_next3_fu_426_p2 = (12'd1 + ap_phi_mux_indvar_flatten3_phi_fu_282_p4);

assign indvar_flatten_next_fu_614_p3 = ((exitcond_flatten_reg_996[0:0] === 1'b1) ? 9'd1 : indvar_flatten_op_reg_1098);

assign indvar_flatten_op_fu_593_p2 = (indvar_flatten_reg_301 + 9'd1);

assign j_2_fu_474_p2 = (5'd1 + j_mid_reg_1007);

assign j_mid_fu_438_p3 = ((exitcond_flatten_fu_432_p2[0:0] === 1'b1) ? 5'd0 : ap_phi_mux_j_phi_fu_317_p4);

assign k_9_1_fu_609_p2 = (k_mid2_reg_1039 + 5'd2);

assign k_mid2_fu_484_p3 = ((tmp_17_fu_479_p2[0:0] === 1'b1) ? 5'd0 : k_reg_324);

assign newIndex7_mid2_cast_fu_710_p1 = newIndex7_mid2_reg_1067_pp0_iter2_reg;

assign newIndex7_mid2_fu_521_p3 = ((exitcond_mid_fu_469_p2[0:0] === 1'b1) ? newIndex_mid1_fu_511_p4 : newIndex7_mid_fu_458_p3);

assign newIndex7_mid_fu_458_p3 = ((exitcond_flatten_reg_996[0:0] === 1'b1) ? 2'd0 : newIndex_reg_947);

assign newIndex9_cast_fu_659_p1 = newIndex8_reg_1072_pp0_iter1_reg;

assign newIndex_mid1_fu_511_p4 = {{j_2_fu_474_p2[4:3]}};

assign newSel1_fu_883_p3 = ((sel_tmp8_mid2_fu_806_p3[0:0] === 1'b1) ? tmp_mid_execute_4_q0 : tmp_mid_execute_3_q0);

assign newSel2_fu_891_p3 = ((sel_tmp4_mid2_fu_789_p3[0:0] === 1'b1) ? tmp_mid_execute_2_q0 : tmp_mid_execute_1_q0);

assign newSel3_fu_899_p3 = ((sel_tmp_mid2_fu_772_p3[0:0] === 1'b1) ? tmp_mid_execute_0_q0 : tmp_mid_execute_7_q0);

assign newSel4_fu_907_p3 = ((or_cond_mid2_fu_836_p3[0:0] === 1'b1) ? newSel_fu_875_p3 : newSel1_fu_883_p3);

assign newSel5_fu_915_p3 = ((or_cond2_mid2_reg_1253[0:0] === 1'b1) ? newSel2_reg_1263 : newSel3_reg_1268);

assign newSel6_fu_920_p3 = ((or_cond3_mid2_reg_1258[0:0] === 1'b1) ? newSel4_reg_1273 : newSel5_fu_915_p3);

assign newSel_fu_875_p3 = ((sel_tmp3_mid2_fu_823_p3[0:0] === 1'b1) ? tmp_mid_execute_6_q0 : tmp_mid_execute_5_q0);

assign not_exitcond_flatten_fu_464_p2 = (exitcond_flatten_reg_996 ^ 1'd1);

assign or_cond1_fu_402_p2 = (sel_tmp8_fu_378_p2 | sel_tmp6_fu_372_p2);

assign or_cond1_mid1_fu_843_p2 = (sel_tmp8_mid1_fu_801_p2 | sel_tmp6_mid1_fu_796_p2);

assign or_cond2_fu_408_p2 = (sel_tmp4_fu_366_p2 | sel_tmp2_fu_360_p2);

assign or_cond2_mid1_fu_849_p2 = (sel_tmp4_mid1_fu_784_p2 | sel_tmp2_mid1_fu_779_p2);

assign or_cond2_mid2_fu_855_p3 = ((exitcond_mid_reg_1028_pp0_iter3_reg[0:0] === 1'b1) ? or_cond2_mid1_fu_849_p2 : or_cond2_mid_fu_759_p2);

assign or_cond2_mid_fu_759_p2 = (or_cond2_reg_977_pp0_iter3_reg & not_exitcond_flatten_reg_1018_pp0_iter3_reg);

assign or_cond3_fu_414_p2 = (or_cond_fu_396_p2 | or_cond1_fu_402_p2);

assign or_cond3_mid1_fu_862_p2 = (or_cond_mid1_fu_830_p2 | or_cond1_mid1_fu_843_p2);

assign or_cond3_mid2_fu_868_p3 = ((exitcond_mid_reg_1028_pp0_iter3_reg[0:0] === 1'b1) ? or_cond3_mid1_fu_862_p2 : or_cond3_mid_fu_763_p2);

assign or_cond3_mid_fu_763_p2 = (or_cond3_reg_982_pp0_iter3_reg & not_exitcond_flatten_reg_1018_pp0_iter3_reg);

assign or_cond_fu_396_p2 = (sel_tmp3_fu_390_p2 | sel_tmp1_fu_384_p2);

assign or_cond_mid1_fu_830_p2 = (sel_tmp3_mid1_fu_818_p2 | sel_tmp1_mid1_fu_813_p2);

assign or_cond_mid2_fu_836_p3 = ((exitcond_mid_reg_1028_pp0_iter3_reg[0:0] === 1'b1) ? or_cond_mid1_fu_830_p2 : or_cond_mid_fu_755_p2);

assign or_cond_mid_fu_755_p2 = (or_cond_reg_972_pp0_iter3_reg & not_exitcond_flatten_reg_1018_pp0_iter3_reg);

assign p_shl10_cast_fu_642_p1 = tmp_fu_635_p3;

assign p_shl7_cast_fu_577_p1 = tmp_22_fu_570_p3;

assign p_shl_cast_fu_566_p1 = tmp_21_fu_559_p3;

assign sel_tmp1_fu_384_p2 = ((tmp_8_fu_340_p1 == 3'd5) ? 1'b1 : 1'b0);

assign sel_tmp1_mid1_fu_813_p2 = ((tmp_10_reg_1052_pp0_iter3_reg == 3'd5) ? 1'b1 : 1'b0);

assign sel_tmp2_fu_360_p2 = ((tmp_8_fu_340_p1 == 3'd1) ? 1'b1 : 1'b0);

assign sel_tmp2_mid1_fu_779_p2 = ((tmp_10_reg_1052_pp0_iter3_reg == 3'd1) ? 1'b1 : 1'b0);

assign sel_tmp3_fu_390_p2 = ((tmp_8_fu_340_p1 == 3'd6) ? 1'b1 : 1'b0);

assign sel_tmp3_mid1_fu_818_p2 = ((tmp_10_reg_1052_pp0_iter3_reg == 3'd6) ? 1'b1 : 1'b0);

assign sel_tmp3_mid2_fu_823_p3 = ((exitcond_mid_reg_1028_pp0_iter3_reg[0:0] === 1'b1) ? sel_tmp3_mid1_fu_818_p2 : sel_tmp3_mid_fu_751_p2);

assign sel_tmp3_mid_fu_751_p2 = (sel_tmp3_reg_967_pp0_iter3_reg & not_exitcond_flatten_reg_1018_pp0_iter3_reg);

assign sel_tmp4_fu_366_p2 = ((tmp_8_fu_340_p1 == 3'd2) ? 1'b1 : 1'b0);

assign sel_tmp4_mid1_fu_784_p2 = ((tmp_10_reg_1052_pp0_iter3_reg == 3'd2) ? 1'b1 : 1'b0);

assign sel_tmp4_mid2_fu_789_p3 = ((exitcond_mid_reg_1028_pp0_iter3_reg[0:0] === 1'b1) ? sel_tmp4_mid1_fu_784_p2 : sel_tmp4_mid_fu_743_p2);

assign sel_tmp4_mid_fu_743_p2 = (sel_tmp4_reg_957_pp0_iter3_reg & not_exitcond_flatten_reg_1018_pp0_iter3_reg);

assign sel_tmp6_fu_372_p2 = ((tmp_8_fu_340_p1 == 3'd3) ? 1'b1 : 1'b0);

assign sel_tmp6_mid1_fu_796_p2 = ((tmp_10_reg_1052_pp0_iter3_reg == 3'd3) ? 1'b1 : 1'b0);

assign sel_tmp8_fu_378_p2 = ((tmp_8_fu_340_p1 == 3'd4) ? 1'b1 : 1'b0);

assign sel_tmp8_mid1_fu_801_p2 = ((tmp_10_reg_1052_pp0_iter3_reg == 3'd4) ? 1'b1 : 1'b0);

assign sel_tmp8_mid2_fu_806_p3 = ((exitcond_mid_reg_1028_pp0_iter3_reg[0:0] === 1'b1) ? sel_tmp8_mid1_fu_801_p2 : sel_tmp8_mid_fu_747_p2);

assign sel_tmp8_mid_fu_747_p2 = (sel_tmp8_reg_962_pp0_iter3_reg & not_exitcond_flatten_reg_1018_pp0_iter3_reg);

assign sel_tmp_fu_354_p2 = ((tmp_8_fu_340_p1 == 3'd0) ? 1'b1 : 1'b0);

assign sel_tmp_mid1_fu_767_p2 = ((tmp_10_reg_1052_pp0_iter3_reg == 3'd0) ? 1'b1 : 1'b0);

assign sel_tmp_mid2_fu_772_p3 = ((exitcond_mid_reg_1028_pp0_iter3_reg[0:0] === 1'b1) ? sel_tmp_mid1_fu_767_p2 : sel_tmp_mid_fu_739_p2);

assign sel_tmp_mid_fu_739_p2 = (sel_tmp_reg_952_pp0_iter3_reg | exitcond_flatten_reg_996_pp0_iter3_reg);

assign storemerge_fu_931_p3 = ((tmp_7_reg_1103_pp0_iter3_reg[0:0] === 1'b1) ? tmp_9_reg_1243 : tmp_4_fu_926_p2);

assign tmp_10_fu_499_p1 = j_2_fu_474_p2[2:0];

assign tmp_13_1_fu_937_p2 = (storemerge_fu_931_p3 + tmp_12_1_reg_1278);

assign tmp_14_fu_699_p3 = {{tmp_mid2_v_reg_1079_pp0_iter2_reg}, {1'd0}};

assign tmp_15_fu_646_p3 = {{tmp_mid2_v_reg_1079_pp0_iter1_reg}, {4'd0}};

assign tmp_16_fu_653_p2 = (tmp_15_fu_646_p3 - p_shl10_cast_fu_642_p1);

assign tmp_17_fu_479_p2 = (exitcond_mid_fu_469_p2 | exitcond_flatten_reg_996);

assign tmp_18_fu_713_p2 = (newIndex7_mid2_cast_fu_710_p1 + tmp_s_fu_694_p2);

assign tmp_19_fu_719_p2 = (newIndex7_mid2_cast_fu_710_p1 + tmp_53_cast_fu_706_p1);

assign tmp_20_fu_662_p2 = ($signed(newIndex9_cast_fu_659_p1) + $signed(tmp_16_fu_653_p2));

assign tmp_21_fu_559_p3 = {{newIndex8_reg_1072}, {4'd0}};

assign tmp_22_fu_570_p3 = {{newIndex8_reg_1072}, {1'd0}};

assign tmp_23_fu_581_p2 = (p_shl_cast_fu_566_p1 + p_shl7_cast_fu_577_p1);

assign tmp_24_fu_587_p2 = (tmp_mid2_cast1_fu_552_p1 + tmp_23_fu_581_p2);

assign tmp_4_fu_926_p2 = (tmp_3_reg_1248 + newSel6_fu_920_p3);

assign tmp_53_cast_fu_706_p1 = tmp_14_fu_699_p3;

assign tmp_56_cast_fu_668_p1 = tmp_16_reg_1148;

assign tmp_58_cast_fu_725_p1 = $signed(tmp_18_reg_1193);

assign tmp_59_cast_fu_730_p1 = tmp_19_reg_1198;

assign tmp_60_cast_fu_672_p1 = $signed(tmp_20_reg_1153);

assign tmp_64_cast_fu_604_p1 = tmp_24_reg_1093;

assign tmp_7_fu_599_p2 = ((k_mid2_reg_1039 == 5'd0) ? 1'b1 : 1'b0);

assign tmp_8_fu_340_p1 = ap_phi_mux_j_phi_fu_317_p4[2:0];

assign tmp_fu_635_p3 = {{tmp_mid2_v_reg_1079_pp0_iter1_reg}, {2'd0}};

assign tmp_mid2_cast1_fu_552_p1 = tmp_mid2_reg_1045;

assign tmp_mid2_cast_25_fu_555_p1 = tmp_mid2_reg_1045;

assign tmp_mid2_cast_fu_691_p1 = tmp_mid2_v_reg_1079_pp0_iter2_reg;

assign tmp_mid2_fu_492_p3 = ((exitcond_mid_fu_469_p2[0:0] === 1'b1) ? j_2_fu_474_p2 : j_mid_reg_1007);

assign tmp_mid2_v_fu_545_p3 = ((exitcond_flatten_reg_996[0:0] === 1'b1) ? i_2_fu_539_p2 : ap_phi_mux_i_phi_fu_293_p4);

assign tmp_mid_execute_0_d0 = tmp_13_1_reg_1283;

assign tmp_mid_execute_1_d0 = tmp_13_1_reg_1283;

assign tmp_mid_execute_2_d0 = tmp_13_1_reg_1283;

assign tmp_mid_execute_3_d0 = tmp_13_1_reg_1283;

assign tmp_mid_execute_4_d0 = tmp_13_1_reg_1283;

assign tmp_mid_execute_5_d0 = tmp_13_1_reg_1283;

assign tmp_mid_execute_6_d0 = tmp_13_1_reg_1283;

assign tmp_mid_execute_7_d0 = tmp_13_1_reg_1283;

assign tmp_s_fu_694_p2 = (tmp_reg_1143_pp0_iter2_reg - tmp_mid2_cast_fu_691_p1);

always @ (posedge ap_clk) begin
    tmp_reg_1143[1:0] <= 2'b00;
    tmp_reg_1143_pp0_iter2_reg[1:0] <= 2'b00;
    tmp_16_reg_1148[1:0] <= 2'b00;
end

endmodule //func1_execute8
