// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module func24 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        C_0_address0,
        C_0_ce0,
        C_0_q0,
        C_1_address0,
        C_1_ce0,
        C_1_q0,
        C_2_address0,
        C_2_ce0,
        C_2_q0,
        C_3_address0,
        C_3_ce0,
        C_3_q0,
        C_4_address0,
        C_4_ce0,
        C_4_q0,
        C_5_address0,
        C_5_ce0,
        C_5_q0,
        C_6_address0,
        C_6_ce0,
        C_6_q0,
        C_7_address0,
        C_7_ce0,
        C_7_q0,
        D_address0,
        D_ce0,
        D_q0,
        tmp_0_address0,
        tmp_0_ce0,
        tmp_0_q0,
        tmp_1_address0,
        tmp_1_ce0,
        tmp_1_q0,
        tmp_2_address0,
        tmp_2_ce0,
        tmp_2_q0,
        tmp_3_address0,
        tmp_3_ce0,
        tmp_3_q0,
        tmp_4_address0,
        tmp_4_ce0,
        tmp_4_q0,
        tmp_5_address0,
        tmp_5_ce0,
        tmp_5_q0,
        tmp_6_address0,
        tmp_6_ce0,
        tmp_6_q0,
        tmp_7_address0,
        tmp_7_ce0,
        tmp_7_q0,
        D_output_address0,
        D_output_ce0,
        D_output_we0,
        D_output_d0
);

parameter    ap_ST_fsm_state1 = 30'd1;
parameter    ap_ST_fsm_state2 = 30'd2;
parameter    ap_ST_fsm_state3 = 30'd4;
parameter    ap_ST_fsm_state4 = 30'd8;
parameter    ap_ST_fsm_state5 = 30'd16;
parameter    ap_ST_fsm_state6 = 30'd32;
parameter    ap_ST_fsm_state7 = 30'd64;
parameter    ap_ST_fsm_state8 = 30'd128;
parameter    ap_ST_fsm_state9 = 30'd256;
parameter    ap_ST_fsm_state10 = 30'd512;
parameter    ap_ST_fsm_state11 = 30'd1024;
parameter    ap_ST_fsm_state12 = 30'd2048;
parameter    ap_ST_fsm_state13 = 30'd4096;
parameter    ap_ST_fsm_state14 = 30'd8192;
parameter    ap_ST_fsm_state15 = 30'd16384;
parameter    ap_ST_fsm_state16 = 30'd32768;
parameter    ap_ST_fsm_state17 = 30'd65536;
parameter    ap_ST_fsm_state18 = 30'd131072;
parameter    ap_ST_fsm_state19 = 30'd262144;
parameter    ap_ST_fsm_state20 = 30'd524288;
parameter    ap_ST_fsm_state21 = 30'd1048576;
parameter    ap_ST_fsm_state22 = 30'd2097152;
parameter    ap_ST_fsm_state23 = 30'd4194304;
parameter    ap_ST_fsm_state24 = 30'd8388608;
parameter    ap_ST_fsm_state25 = 30'd16777216;
parameter    ap_ST_fsm_state26 = 30'd33554432;
parameter    ap_ST_fsm_state27 = 30'd67108864;
parameter    ap_ST_fsm_state28 = 30'd134217728;
parameter    ap_ST_fsm_state29 = 30'd268435456;
parameter    ap_ST_fsm_state30 = 30'd536870912;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [6:0] C_0_address0;
output   C_0_ce0;
input  [31:0] C_0_q0;
output  [6:0] C_1_address0;
output   C_1_ce0;
input  [31:0] C_1_q0;
output  [5:0] C_2_address0;
output   C_2_ce0;
input  [31:0] C_2_q0;
output  [5:0] C_3_address0;
output   C_3_ce0;
input  [31:0] C_3_q0;
output  [5:0] C_4_address0;
output   C_4_ce0;
input  [31:0] C_4_q0;
output  [5:0] C_5_address0;
output   C_5_ce0;
input  [31:0] C_5_q0;
output  [5:0] C_6_address0;
output   C_6_ce0;
input  [31:0] C_6_q0;
output  [5:0] C_7_address0;
output   C_7_ce0;
input  [31:0] C_7_q0;
output  [8:0] D_address0;
output   D_ce0;
input  [31:0] D_q0;
output  [5:0] tmp_0_address0;
output   tmp_0_ce0;
input  [31:0] tmp_0_q0;
output  [5:0] tmp_1_address0;
output   tmp_1_ce0;
input  [31:0] tmp_1_q0;
output  [4:0] tmp_2_address0;
output   tmp_2_ce0;
input  [31:0] tmp_2_q0;
output  [4:0] tmp_3_address0;
output   tmp_3_ce0;
input  [31:0] tmp_3_q0;
output  [4:0] tmp_4_address0;
output   tmp_4_ce0;
input  [31:0] tmp_4_q0;
output  [4:0] tmp_5_address0;
output   tmp_5_ce0;
input  [31:0] tmp_5_q0;
output  [4:0] tmp_6_address0;
output   tmp_6_ce0;
input  [31:0] tmp_6_q0;
output  [4:0] tmp_7_address0;
output   tmp_7_ce0;
input  [31:0] tmp_7_q0;
output  [8:0] D_output_address0;
output   D_output_ce0;
output   D_output_we0;
output  [31:0] D_output_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg C_0_ce0;
reg C_1_ce0;
reg C_2_ce0;
reg C_3_ce0;
reg C_4_ce0;
reg C_5_ce0;
reg C_6_ce0;
reg C_7_ce0;
reg D_ce0;
reg tmp_0_ce0;
reg tmp_1_ce0;
reg tmp_2_ce0;
reg tmp_3_ce0;
reg tmp_4_ce0;
reg tmp_5_ce0;
reg tmp_6_ce0;
reg tmp_7_ce0;
reg D_output_ce0;
reg D_output_we0;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [29:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] i_1_fu_359_p2;
reg   [4:0] i_1_reg_629;
wire    ap_CS_fsm_state2;
wire   [9:0] tmp_2_17_fu_389_p2;
reg   [9:0] tmp_2_17_reg_634;
wire   [0:0] exitcond2_fu_353_p2;
wire   [6:0] tmp_4_19_fu_403_p2;
reg   [6:0] tmp_4_19_reg_639;
wire   [6:0] tmp_43_cast_fu_417_p1;
reg   [6:0] tmp_43_cast_reg_644;
wire   [4:0] j_1_fu_427_p2;
reg   [4:0] j_1_reg_652;
wire    ap_CS_fsm_state3;
wire   [9:0] tmp_7_22_fu_437_p2;
reg   [9:0] tmp_7_22_reg_657;
wire   [0:0] exitcond1_fu_421_p2;
wire    ap_CS_fsm_state4;
reg   [8:0] D_output_addr_reg_667;
reg  signed [31:0] D_load_reg_672;
wire    ap_CS_fsm_state5;
wire   [31:0] grp_fu_447_p2;
reg   [31:0] sum_reg_677;
wire    ap_CS_fsm_state10;
wire   [7:0] tmp_4_cast5_fu_452_p1;
reg   [7:0] tmp_4_cast5_reg_682;
wire    ap_CS_fsm_state11;
wire   [7:0] tmp_11_fu_500_p2;
reg   [7:0] tmp_11_reg_687;
wire    ap_CS_fsm_state12;
wire   [6:0] tmp_12_fu_505_p2;
reg   [6:0] tmp_12_reg_692;
wire   [6:0] tmp_13_fu_510_p2;
reg   [6:0] tmp_13_reg_697;
wire    ap_CS_fsm_state13;
reg   [5:0] C_2_addr_reg_712;
reg   [5:0] C_3_addr_reg_717;
reg   [5:0] C_4_addr_reg_722;
reg   [5:0] C_5_addr_reg_727;
reg   [5:0] C_6_addr_reg_732;
reg   [5:0] C_7_addr_reg_737;
reg  signed [31:0] tmp_0_load_reg_752;
wire    ap_CS_fsm_state14;
reg  signed [31:0] C_0_load_reg_757;
reg  signed [31:0] tmp_1_load_reg_762;
reg  signed [31:0] C_1_load_reg_767;
wire   [31:0] grp_fu_531_p2;
reg   [31:0] tmp_6_23_reg_772;
wire    ap_CS_fsm_state19;
wire   [31:0] grp_fu_535_p2;
reg   [31:0] tmp_6_1_reg_777;
reg   [4:0] tmp_2_addr_reg_782;
wire    ap_CS_fsm_state20;
reg   [4:0] tmp_3_addr_reg_787;
reg   [4:0] tmp_4_addr_reg_792;
reg   [4:0] tmp_5_addr_reg_797;
wire   [31:0] sum_1_1_fu_552_p2;
reg   [31:0] sum_1_1_reg_812;
wire   [4:0] k_8_7_fu_570_p2;
reg   [4:0] k_8_7_reg_821;
wire   [0:0] exitcond_2_fu_564_p2;
reg  signed [31:0] tmp_6_load_reg_826;
wire    ap_CS_fsm_state21;
reg  signed [31:0] C_6_load_reg_831;
reg  signed [31:0] tmp_7_load_reg_836;
reg  signed [31:0] C_7_load_reg_841;
reg  signed [31:0] tmp_2_load_reg_846;
wire    ap_CS_fsm_state22;
reg  signed [31:0] C_2_load_reg_851;
reg  signed [31:0] tmp_3_load_reg_856;
reg  signed [31:0] C_3_load_reg_861;
reg  signed [31:0] tmp_4_load_reg_866;
reg  signed [31:0] C_4_load_reg_871;
reg  signed [31:0] tmp_5_load_reg_876;
reg  signed [31:0] C_5_load_reg_881;
wire   [31:0] grp_fu_576_p2;
reg   [31:0] tmp_6_6_reg_886;
wire    ap_CS_fsm_state26;
wire   [31:0] grp_fu_580_p2;
reg   [31:0] tmp_6_7_reg_891;
wire   [31:0] grp_fu_584_p2;
reg   [31:0] tmp_6_2_reg_896;
wire    ap_CS_fsm_state27;
wire   [31:0] grp_fu_588_p2;
reg   [31:0] tmp_6_3_reg_901;
wire   [31:0] grp_fu_592_p2;
reg   [31:0] tmp_6_4_reg_906;
wire   [31:0] grp_fu_596_p2;
reg   [31:0] tmp_6_5_reg_911;
wire   [31:0] tmp5_fu_600_p2;
reg   [31:0] tmp5_reg_916;
wire   [31:0] tmp2_fu_604_p2;
reg   [31:0] tmp2_reg_921;
wire    ap_CS_fsm_state28;
wire   [31:0] tmp3_fu_612_p2;
reg   [31:0] tmp3_reg_926;
wire   [31:0] sum_1_7_fu_621_p2;
wire    ap_CS_fsm_state29;
reg   [4:0] i_reg_309;
reg    ap_block_state1;
reg   [4:0] j_reg_320;
wire    ap_CS_fsm_state30;
reg   [4:0] k_reg_332;
reg   [31:0] sum1_reg_344;
wire  signed [63:0] tmp_44_cast_fu_442_p1;
wire  signed [63:0] tmp_48_cast_fu_515_p1;
wire  signed [63:0] tmp_49_cast_fu_526_p1;
wire   [63:0] tmp_50_cast_fu_539_p1;
wire   [7:0] tmp_1_16_fu_377_p3;
wire   [9:0] tmp_s_fu_369_p3;
wire   [9:0] p_shl2_cast_fu_385_p1;
wire   [6:0] tmp_3_18_fu_395_p3;
wire   [6:0] tmp_cast_fu_365_p1;
wire   [5:0] tmp_5_20_fu_409_p3;
wire   [9:0] tmp_4_cast_fu_433_p1;
wire   [9:0] grp_fu_447_p1;
wire    ap_CS_fsm_state6;
wire   [1:0] newIndex_fu_456_p4;
wire   [6:0] tmp_8_fu_470_p3;
wire   [4:0] tmp_9_fu_482_p3;
wire   [7:0] p_shl3_cast_fu_478_p1;
wire   [7:0] p_shl4_cast_fu_490_p1;
wire   [7:0] tmp_10_fu_494_p2;
wire   [6:0] newIndex6_cast_fu_466_p1;
wire    ap_CS_fsm_state15;
wire   [31:0] tmp_fu_548_p2;
wire   [4:0] k_8_s_fu_558_p2;
wire    ap_CS_fsm_state23;
wire   [31:0] tmp4_fu_608_p2;
wire   [31:0] tmp1_fu_617_p2;
reg   [29:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 30'd1;
end

kernel_2mm_wrappedEe #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 32 ))
kernel_2mm_wrappedEe_U92(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(D_load_reg_672),
    .din1(grp_fu_447_p1),
    .ce(1'b1),
    .dout(grp_fu_447_p2)
);

kernel_2mm_wrappecud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kernel_2mm_wrappecud_U93(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(C_0_load_reg_757),
    .din1(tmp_0_load_reg_752),
    .ce(1'b1),
    .dout(grp_fu_531_p2)
);

kernel_2mm_wrappecud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kernel_2mm_wrappecud_U94(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(C_1_load_reg_767),
    .din1(tmp_1_load_reg_762),
    .ce(1'b1),
    .dout(grp_fu_535_p2)
);

kernel_2mm_wrappecud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kernel_2mm_wrappecud_U95(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_6_load_reg_826),
    .din1(C_6_load_reg_831),
    .ce(1'b1),
    .dout(grp_fu_576_p2)
);

kernel_2mm_wrappecud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kernel_2mm_wrappecud_U96(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_7_load_reg_836),
    .din1(C_7_load_reg_841),
    .ce(1'b1),
    .dout(grp_fu_580_p2)
);

kernel_2mm_wrappecud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kernel_2mm_wrappecud_U97(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_2_load_reg_846),
    .din1(C_2_load_reg_851),
    .ce(1'b1),
    .dout(grp_fu_584_p2)
);

kernel_2mm_wrappecud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kernel_2mm_wrappecud_U98(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_3_load_reg_856),
    .din1(C_3_load_reg_861),
    .ce(1'b1),
    .dout(grp_fu_588_p2)
);

kernel_2mm_wrappecud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kernel_2mm_wrappecud_U99(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_4_load_reg_866),
    .din1(C_4_load_reg_871),
    .ce(1'b1),
    .dout(grp_fu_592_p2)
);

kernel_2mm_wrappecud #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kernel_2mm_wrappecud_U100(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_5_load_reg_876),
    .din1(C_5_load_reg_881),
    .ce(1'b1),
    .dout(grp_fu_596_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond2_fu_353_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond1_fu_421_p2 == 1'd1))) begin
        i_reg_309 <= i_1_reg_629;
    end else if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_309 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond2_fu_353_p2 == 1'd0))) begin
        j_reg_320 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        j_reg_320 <= j_1_reg_652;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        k_reg_332 <= k_8_7_reg_821;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        k_reg_332 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        sum1_reg_344 <= sum_1_7_fu_621_p2;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        sum1_reg_344 <= sum_reg_677;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        C_0_load_reg_757 <= C_0_q0;
        C_1_load_reg_767 <= C_1_q0;
        tmp_0_load_reg_752 <= tmp_0_q0;
        tmp_1_load_reg_762 <= tmp_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        C_2_addr_reg_712 <= tmp_48_cast_fu_515_p1;
        C_3_addr_reg_717 <= tmp_48_cast_fu_515_p1;
        C_4_addr_reg_722 <= tmp_48_cast_fu_515_p1;
        C_5_addr_reg_727 <= tmp_48_cast_fu_515_p1;
        C_6_addr_reg_732 <= tmp_48_cast_fu_515_p1;
        C_7_addr_reg_737 <= tmp_48_cast_fu_515_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        C_2_load_reg_851 <= C_2_q0;
        C_3_load_reg_861 <= C_3_q0;
        C_4_load_reg_871 <= C_4_q0;
        C_5_load_reg_881 <= C_5_q0;
        tmp_2_load_reg_846 <= tmp_2_q0;
        tmp_3_load_reg_856 <= tmp_3_q0;
        tmp_4_load_reg_866 <= tmp_4_q0;
        tmp_5_load_reg_876 <= tmp_5_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        C_6_load_reg_831 <= C_6_q0;
        C_7_load_reg_841 <= C_7_q0;
        tmp_6_load_reg_826 <= tmp_6_q0;
        tmp_7_load_reg_836 <= tmp_7_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        D_load_reg_672 <= D_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        D_output_addr_reg_667 <= tmp_44_cast_fu_442_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_1_reg_629 <= i_1_fu_359_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        j_1_reg_652 <= j_1_fu_427_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state20) & (exitcond_2_fu_564_p2 == 1'd0))) begin
        k_8_7_reg_821 <= k_8_7_fu_570_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        sum_1_1_reg_812 <= sum_1_1_fu_552_p2;
        tmp_2_addr_reg_782 <= tmp_50_cast_fu_539_p1;
        tmp_3_addr_reg_787 <= tmp_50_cast_fu_539_p1;
        tmp_4_addr_reg_792 <= tmp_50_cast_fu_539_p1;
        tmp_5_addr_reg_797 <= tmp_50_cast_fu_539_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        sum_reg_677 <= grp_fu_447_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        tmp2_reg_921 <= tmp2_fu_604_p2;
        tmp3_reg_926 <= tmp3_fu_612_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        tmp5_reg_916 <= tmp5_fu_600_p2;
        tmp_6_2_reg_896 <= grp_fu_584_p2;
        tmp_6_3_reg_901 <= grp_fu_588_p2;
        tmp_6_4_reg_906 <= grp_fu_592_p2;
        tmp_6_5_reg_911 <= grp_fu_596_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tmp_11_reg_687 <= tmp_11_fu_500_p2;
        tmp_12_reg_692 <= tmp_12_fu_505_p2;
        tmp_13_reg_697 <= tmp_13_fu_510_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond2_fu_353_p2 == 1'd0))) begin
        tmp_2_17_reg_634[9 : 3] <= tmp_2_17_fu_389_p2[9 : 3];
        tmp_43_cast_reg_644[5 : 1] <= tmp_43_cast_fu_417_p1[5 : 1];
        tmp_4_19_reg_639 <= tmp_4_19_fu_403_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        tmp_4_cast5_reg_682[4 : 0] <= tmp_4_cast5_fu_452_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        tmp_6_1_reg_777 <= grp_fu_535_p2;
        tmp_6_23_reg_772 <= grp_fu_531_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        tmp_6_6_reg_886 <= grp_fu_576_p2;
        tmp_6_7_reg_891 <= grp_fu_580_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond1_fu_421_p2 == 1'd0))) begin
        tmp_7_22_reg_657 <= tmp_7_22_fu_437_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        C_0_ce0 = 1'b1;
    end else begin
        C_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        C_1_ce0 = 1'b1;
    end else begin
        C_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        C_2_ce0 = 1'b1;
    end else begin
        C_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        C_3_ce0 = 1'b1;
    end else begin
        C_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        C_4_ce0 = 1'b1;
    end else begin
        C_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        C_5_ce0 = 1'b1;
    end else begin
        C_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        C_6_ce0 = 1'b1;
    end else begin
        C_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        C_7_ce0 = 1'b1;
    end else begin
        C_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        D_ce0 = 1'b1;
    end else begin
        D_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        D_output_ce0 = 1'b1;
    end else begin
        D_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        D_output_we0 = 1'b1;
    end else begin
        D_output_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond2_fu_353_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond2_fu_353_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_0_ce0 = 1'b1;
    end else begin
        tmp_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_1_ce0 = 1'b1;
    end else begin
        tmp_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        tmp_2_ce0 = 1'b1;
    end else begin
        tmp_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        tmp_3_ce0 = 1'b1;
    end else begin
        tmp_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        tmp_4_ce0 = 1'b1;
    end else begin
        tmp_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        tmp_5_ce0 = 1'b1;
    end else begin
        tmp_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        tmp_6_ce0 = 1'b1;
    end else begin
        tmp_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        tmp_7_ce0 = 1'b1;
    end else begin
        tmp_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (exitcond2_fu_353_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (exitcond1_fu_421_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((exitcond_2_fu_564_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_0_address0 = tmp_48_cast_fu_515_p1;

assign C_1_address0 = tmp_48_cast_fu_515_p1;

assign C_2_address0 = C_2_addr_reg_712;

assign C_3_address0 = C_3_addr_reg_717;

assign C_4_address0 = C_4_addr_reg_722;

assign C_5_address0 = C_5_addr_reg_727;

assign C_6_address0 = C_6_addr_reg_732;

assign C_7_address0 = C_7_addr_reg_737;

assign D_address0 = tmp_44_cast_fu_442_p1;

assign D_output_address0 = D_output_addr_reg_667;

assign D_output_d0 = sum_1_1_reg_812;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign exitcond1_fu_421_p2 = ((j_reg_320 == 5'd24) ? 1'b1 : 1'b0);

assign exitcond2_fu_353_p2 = ((i_reg_309 == 5'd16) ? 1'b1 : 1'b0);

assign exitcond_2_fu_564_p2 = ((k_8_s_fu_558_p2 == 5'd18) ? 1'b1 : 1'b0);

assign grp_fu_447_p1 = 32'd321;

assign i_1_fu_359_p2 = (i_reg_309 + 5'd1);

assign j_1_fu_427_p2 = (j_reg_320 + 5'd1);

assign k_8_7_fu_570_p2 = (k_reg_332 + 5'd8);

assign k_8_s_fu_558_p2 = (k_reg_332 | 5'd2);

assign newIndex6_cast_fu_466_p1 = newIndex_fu_456_p4;

assign newIndex_fu_456_p4 = {{k_reg_332[4:3]}};

assign p_shl2_cast_fu_385_p1 = tmp_1_16_fu_377_p3;

assign p_shl3_cast_fu_478_p1 = tmp_8_fu_470_p3;

assign p_shl4_cast_fu_490_p1 = tmp_9_fu_482_p3;

assign sum_1_1_fu_552_p2 = (sum1_reg_344 + tmp_fu_548_p2);

assign sum_1_7_fu_621_p2 = (tmp3_reg_926 + tmp1_fu_617_p2);

assign tmp1_fu_617_p2 = (tmp2_reg_921 + sum_1_1_reg_812);

assign tmp2_fu_604_p2 = (tmp_6_2_reg_896 + tmp_6_3_reg_901);

assign tmp3_fu_612_p2 = (tmp5_reg_916 + tmp4_fu_608_p2);

assign tmp4_fu_608_p2 = (tmp_6_4_reg_906 + tmp_6_5_reg_911);

assign tmp5_fu_600_p2 = (tmp_6_6_reg_886 + tmp_6_7_reg_891);

assign tmp_0_address0 = tmp_49_cast_fu_526_p1;

assign tmp_10_fu_494_p2 = (p_shl3_cast_fu_478_p1 - p_shl4_cast_fu_490_p1);

assign tmp_11_fu_500_p2 = (tmp_10_fu_494_p2 + tmp_4_cast5_reg_682);

assign tmp_12_fu_505_p2 = (tmp_4_19_reg_639 + newIndex6_cast_fu_466_p1);

assign tmp_13_fu_510_p2 = (tmp_43_cast_reg_644 + newIndex6_cast_fu_466_p1);

assign tmp_1_16_fu_377_p3 = {{i_reg_309}, {3'd0}};

assign tmp_1_address0 = tmp_49_cast_fu_526_p1;

assign tmp_2_17_fu_389_p2 = (tmp_s_fu_369_p3 - p_shl2_cast_fu_385_p1);

assign tmp_2_address0 = tmp_2_addr_reg_782;

assign tmp_3_18_fu_395_p3 = {{i_reg_309}, {2'd0}};

assign tmp_3_address0 = tmp_3_addr_reg_787;

assign tmp_43_cast_fu_417_p1 = tmp_5_20_fu_409_p3;

assign tmp_44_cast_fu_442_p1 = $signed(tmp_7_22_reg_657);

assign tmp_48_cast_fu_515_p1 = $signed(tmp_11_reg_687);

assign tmp_49_cast_fu_526_p1 = $signed(tmp_12_reg_692);

assign tmp_4_19_fu_403_p2 = (tmp_3_18_fu_395_p3 - tmp_cast_fu_365_p1);

assign tmp_4_address0 = tmp_4_addr_reg_792;

assign tmp_4_cast5_fu_452_p1 = j_reg_320;

assign tmp_4_cast_fu_433_p1 = j_reg_320;

assign tmp_50_cast_fu_539_p1 = tmp_13_reg_697;

assign tmp_5_20_fu_409_p3 = {{i_reg_309}, {1'd0}};

assign tmp_5_address0 = tmp_5_addr_reg_797;

assign tmp_6_address0 = tmp_50_cast_fu_539_p1;

assign tmp_7_22_fu_437_p2 = (tmp_2_17_reg_634 + tmp_4_cast_fu_433_p1);

assign tmp_7_address0 = tmp_50_cast_fu_539_p1;

assign tmp_8_fu_470_p3 = {{newIndex_fu_456_p4}, {5'd0}};

assign tmp_9_fu_482_p3 = {{newIndex_fu_456_p4}, {3'd0}};

assign tmp_cast_fu_365_p1 = i_reg_309;

assign tmp_fu_548_p2 = (tmp_6_1_reg_777 + tmp_6_23_reg_772);

assign tmp_s_fu_369_p3 = {{i_reg_309}, {5'd0}};

always @ (posedge ap_clk) begin
    tmp_2_17_reg_634[2:0] <= 3'b000;
    tmp_43_cast_reg_644[0] <= 1'b0;
    tmp_43_cast_reg_644[6] <= 1'b0;
    tmp_4_cast5_reg_682[7:5] <= 3'b000;
end

endmodule //func24
