# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config  -ruleid {10}  -id {Synth 8-350}  -string {{WARNING: [Synth 8-350] instance 'processing_system7_0' of module 'zedboard_base_processing_system7_0_0' requires 114 connections, but only 103 given [/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/synth/zedboard_base.v:1126]}}  -suppress 
set_msg_config  -ruleid {100}  -id {Vivado_Tcl 4-198}  -string {{INFO: [Vivado_Tcl 4-198] DRC finished with 0 Errors}}  -suppress 
set_msg_config  -ruleid {101}  -id {Vivado_Tcl 4-199}  -string {{INFO: [Vivado_Tcl 4-199] Please refer to the DRC report (report_drc) for more information.}}  -suppress 
set_msg_config  -ruleid {102}  -id {Route 35-254}  -string {{INFO: [Route 35-254] Multithreading enabled for route_design using a maximum of 4 CPUs}}  -suppress 
set_msg_config  -ruleid {103}  -id {Route 35-416}  -string {{INFO: [Route 35-416] Intermediate Timing Summary | WNS=-0.179 | TNS=-3.504 | WHS=-0.347 | THS=-773.383|}}  -suppress 
set_msg_config  -ruleid {104}  -id {Route 35-57}  -string {{INFO: [Route 35-57] Estimated Timing Summary | WNS=-0.631 | TNS=-12.151| WHS=0.023  | THS=0.000  |}}  -suppress 
set_msg_config  -ruleid {105}  -id {Route 35-328}  -string {{WARNING: [Route 35-328] Router estimated timing not met.
Resolution: For a complete and accurate timing signoff, report_timing_summary must be run after route_design. Alternatively, route_design can be run with the -timing_summary option to enable a complete timing signoff at the end of route_design.}}  -suppress 
set_msg_config  -ruleid {106}  -id {Route 35-16}  -string {{INFO: [Route 35-16] Router Completed Successfully}}  -suppress 
set_msg_config  -ruleid {108}  -id {Timing 38-480}  -string {{INFO: [Timing 38-480] Writing timing data to binary archive.}}  -suppress 
set_msg_config  -ruleid {109}  -id {Common 17-1381}  -string {{INFO: [Common 17-1381] The checkpoint '/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/impl_1/zedboard_base_wrapper_routed.dcp' has been generated.}}  -suppress 
set_msg_config  -ruleid {11}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design s00_couplers_imp_GCE1M4 has unconnected port M_ACLK}}  -suppress 
set_msg_config  -ruleid {111}  -id {Coretcl 2-168}  -string {{INFO: [Coretcl 2-168] The results of DRC are in file /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/impl_1/zedboard_base_wrapper_drc_routed.rpt.}}  -suppress 
set_msg_config  -ruleid {112}  -id {runtcl-4}  -string {{INFO: [runtcl-4] Executing : report_drc -file zedboard_base_wrapper_drc_routed.rpt -pb zedboard_base_wrapper_drc_routed.pb -rpx zedboard_base_wrapper_drc_routed.rpx}}  -suppress 
set_msg_config  -ruleid {113}  -id {Timing 38-35}  -string {{INFO: [Timing 38-35] Done setting XDC timing constraints.}}  -suppress 
set_msg_config  -ruleid {114}  -id {DRC 23-133}  -string {{INFO: [DRC 23-133] Running Methodology with 4 threads}}  -suppress 
set_msg_config  -ruleid {115}  -id {Coretcl 2-1520}  -string {{INFO: [Coretcl 2-1520] The results of Report Methodology are in file /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/impl_1/zedboard_base_wrapper_methodology_drc_routed.rpt.}}  -suppress 
set_msg_config  -ruleid {116}  -id {Timing 38-282}  -string {{CRITICAL WARNING: [Timing 38-282] The design failed to meet the timing requirements. Please see the timing summary report for details on the timing violations.}}  -suppress 
set_msg_config  -ruleid {117}  -id {Vivado_Tcl 4-545}  -string {{INFO: [Vivado_Tcl 4-545] No incremental reuse to report, no incremental placement and routing data was found.}}  -suppress 
set_msg_config  -ruleid {118}  -id {Timing 38-91}  -string {{INFO: [Timing 38-91] UpdateTimingParams: Speed grade: -1, Delay Type: min_max, Timing Stage: Requireds.}}  -suppress 
set_msg_config  -ruleid {119}  -id {Timing 38-191}  -string {{INFO: [Timing 38-191] Multithreading enabled for timing update using a maximum of 4 CPUs}}  -suppress 
set_msg_config  -ruleid {120}  -id {Memdata 28-167}  -string {{INFO: [Memdata 28-167] Found XPM memory block zedboard_base_i/axi_smc/inst/s04_nodes/s04_w_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory/xpm_memory_base_inst with a P_MEMORY_PRIMITIVE property set to distributed. A value of block is required. You will not be able to use the updatemem program to update the bitstream with new data for the zedboard_base_i/axi_smc/inst/s04_nodes/s04_w_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory/xpm_memory_base_inst block.}}  -suppress 
set_msg_config  -ruleid {121}  -string {{Command: write_bitstream -force zedboard_base_wrapper.bit}}  -suppress 
set_msg_config  -ruleid {122}  -id {Common 17-349}  -string {{INFO: [Common 17-349] Got license for feature 'Implementation' and/or device 'xc7z020'}}  -suppress 
set_msg_config  -ruleid {123}  -id {DRC 23-27}  -string {{INFO: [DRC 23-27] Running DRC with 4 threads}}  -suppress 
set_msg_config  -ruleid {124}  -id {DRC DPOP-2}  -string {{WARNING: [DRC DPOP-2] MREG Output pipelining: DSP zedboard_base_i/zedboard_base_kernel_0/inst/inst/kernel_2mm_U0/func15_U0/grp_func1_execute8_fu_66/kernel_2mm_wrappecud_U45/kernel_2mm_wrappecud_MulnS_1_U/buff0_reg multiplier stage zedboard_base_i/zedboard_base_kernel_0/inst/inst/kernel_2mm_U0/func15_U0/grp_func1_execute8_fu_66/kernel_2mm_wrappecud_U45/kernel_2mm_wrappecud_MulnS_1_U/buff0_reg/P[47:0] is not pipelined (MREG=0). Pipelining the multiplier function will improve performance and will save significant power so it is suggested whenever possible to fully pipeline this function.  If this multiplier was inferred, it is suggested to describe an additional register stage after this function.  If there is no registered adder/accumulator following the multiply function, two pipeline stages are suggested to allow both the MREG and PREG registers to be used.  If the DSP48 was instantiated in the design, it is suggested to set both the MREG and PREG attributes to 1 when performing multiply functions.}}  -suppress 
set_msg_config  -ruleid {125}  -id {Vivado 12-3199}  -string {{INFO: [Vivado 12-3199] DRC finished with 0 Errors, 11 Warnings}}  -suppress 
set_msg_config  -ruleid {126}  -id {Vivado 12-3200}  -string {{INFO: [Vivado 12-3200] Please refer to the DRC report (report_drc) for more information.}}  -suppress 
set_msg_config  -ruleid {127}  -id {Designutils 20-2272}  -string {{INFO: [Designutils 20-2272] Running write_bitstream with 4 threads.}}  -suppress 
set_msg_config  -ruleid {128}  -id {Vivado 12-1842}  -string {{INFO: [Vivado 12-1842] Bitgen Completed Successfully.}}  -suppress 
set_msg_config  -ruleid {129}  -id {Project 1-120}  -string {{INFO: [Project 1-120] WebTalk data collection is mandatory when using a WebPACK part without a full Vivado license. To see the specific WebTalk data collected for your design, open the usage_statistics_webtalk.html or usage_statistics_webtalk.xml file in the implementation directory.}}  -suppress 
set_msg_config  -ruleid {13}  -id {Synth 8-5578}  -string {{INFO: [Synth 8-5578] Moved timing constraint from pin 'zedboard_base_i/processing_system7_0/FCLK_CLK0' to pin 'zedboard_base_i/processing_system7_0/bbstub_FCLK_CLK0/O'}}  -suppress 
set_msg_config  -ruleid {130}  -id {Common 17-186}  -string {{INFO: [Common 17-186] '/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/impl_1/usage_statistics_webtalk.xml' has been successfully sent to Xilinx on Fri Sep  6 14:17:00 2019. For additional details about this file, please refer to the WebTalk help file at /opt/Xilinx_201802/Vivado/2018.2/doc/webtalk_introduction.html.}}  -suppress 
set_msg_config  -ruleid {131}  -id {Common 17-83}  -string {{INFO: [Common 17-83] Releasing license: Implementation}}  -suppress 
set_msg_config  -ruleid {134}  -id {Synth 8-6157}  -string {{INFO: [Synth 8-6157] synthesizing module 'zedboard_base' [/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/synth/zedboard_base.v:582]}}  -suppress 
set_msg_config  -ruleid {135}  -id {Synth 8-6155}  -string {{INFO: [Synth 8-6155] done synthesizing module 'zedboard_base_processing_system7_0_0' (2#1) [/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/synth_1/.Xil/Vivado-11605-tingyuan-OptiPlex-9010/realtime/zedboard_base_processing_system7_0_0_stub.v:6]}}  -suppress 
set_msg_config  -ruleid {136}  -id {Synth 8-350}  -string {{WARNING: [Synth 8-350] instance 'xbar' of module 'zedboard_base_xbar_0' requires 40 connections, but only 38 given [/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/synth/zedboard_base.v:2048]}}  -suppress 
set_msg_config  -ruleid {137}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design s00_couplers_imp_GCE1M4 has unconnected port M_ARESETN}}  -suppress 
set_msg_config  -ruleid {138}  -string {{Starting synth_design}}  -suppress 
set_msg_config  -ruleid {139}  -id {Synth 8-5534}  -string {{INFO: [Synth 8-5534] Detected attribute (* keep = "true" *) [/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v:1349]}}  -suppress 
set_msg_config  -ruleid {14}  -id {Synth 8-5819}  -string {{INFO: [Synth 8-5819] Moved 1 constraints on hierarchical pins to their respective driving/loading pins}}  -suppress 
set_msg_config  -ruleid {140}  -id {Synth 8-6157}  -string {{INFO: [Synth 8-6157] synthesizing module 'processing_system7_v5_5_processing_system7' [/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v:162]}}  -suppress 
set_msg_config  -ruleid {141}  -id {Synth 8-6155}  -string {{INFO: [Synth 8-6155] done synthesizing module 'BIBUF' (2#1) [/opt/Xilinx_201802/Vivado/2018.2/scripts/rt/data/unisim_comp.v:270]}}  -suppress 
set_msg_config  -ruleid {142}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design processing_system7_v5_5_processing_system7 has unconnected port ENET0_GMII_CRS}}  -suppress 
set_msg_config  -ruleid {143}  -id {IP_Flow 19-1700}  -string {{INFO: [IP_Flow 19-1700] Loaded user IP repository '/home/tingyuan/Dropbox/Hi-ClockFLow_Benchmarks'.}}  -suppress 
set_msg_config  -ruleid {144}  -string {{Design is defaulting to srcset: sources_1}}  -suppress 
set_msg_config  -ruleid {145}  -id {Project 1-454}  -string {{INFO: [Project 1-454] Reading design checkpoint '/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_processing_system7_0_0/zedboard_base_processing_system7_0_0.dcp' for cell 'zedboard_base_i/processing_system7_0'}}  -suppress 
set_msg_config  -ruleid {147}  -id {Opt 31-138}  -string {{INFO: [Opt 31-138] Pushed 6 inverter(s) to 49 load pin(s).}}  -suppress 
set_msg_config  -ruleid {148}  -id {Opt 31-389}  -string {{INFO: [Opt 31-389] Phase Constant propagation created 160 cells and removed 3913 cells}}  -suppress 
set_msg_config  -ruleid {150}  -id {runtcl-4}  -string {{INFO: [runtcl-4] Executing : report_utilization -file zedboard_base_wrapper_utilization_placed.rpt -pb zedboard_base_wrapper_utilization_placed.pb}}  -suppress 
set_msg_config  -ruleid {152}  -id {Route 35-416}  -string {{INFO: [Route 35-416] Intermediate Timing Summary | WNS=-0.631 | TNS=-31.247| WHS=N/A    | THS=N/A    |}}  -suppress 
set_msg_config  -ruleid {153}  -id {runtcl-4}  -string {{INFO: [runtcl-4] Executing : report_methodology -file zedboard_base_wrapper_methodology_drc_routed.rpt -pb zedboard_base_wrapper_methodology_drc_routed.pb -rpx zedboard_base_wrapper_methodology_drc_routed.rpx}}  -suppress 
set_msg_config  -ruleid {154}  -id {Memdata 28-167}  -string {{INFO: [Memdata 28-167] Found XPM memory block zedboard_base_i/axi_smc/inst/s04_nodes/s04_w_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory/xpm_memory_base_inst with a P_MEMORY_PRIMITIVE property set to distributed. A value of block is required. You will not be able to use the updatemem program to update the bitstream with new data for the zedboard_base_i/axi_smc/inst/s04_nodes/s04_w_node/inst/inst_mi_handler/gen_normal_area.gen_fifo_req.inst_fifo_req/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory/xpm_memory_base_inst block.}}  -suppress 
set_msg_config  -ruleid {155}  -string {{Attempting to get a license for feature 'Implementation' and/or device 'xc7z020'}}  -suppress 
set_msg_config  -ruleid {156}  -id {DRC DPOP-2}  -string {{WARNING: [DRC DPOP-2] MREG Output pipelining: DSP zedboard_base_i/zedboard_base_kernel_0/inst/inst/kernel_2mm_U0/func15_U0/grp_func1_execute8_fu_66/kernel_2mm_wrappecud_U46/kernel_2mm_wrappecud_MulnS_1_U/buff0_reg multiplier stage zedboard_base_i/zedboard_base_kernel_0/inst/inst/kernel_2mm_U0/func15_U0/grp_func1_execute8_fu_66/kernel_2mm_wrappecud_U46/kernel_2mm_wrappecud_MulnS_1_U/buff0_reg/P[47:0] is not pipelined (MREG=0). Pipelining the multiplier function will improve performance and will save significant power so it is suggested whenever possible to fully pipeline this function.  If this multiplier was inferred, it is suggested to describe an additional register stage after this function.  If there is no registered adder/accumulator following the multiply function, two pipeline stages are suggested to allow both the MREG and PREG registers to be used.  If the DSP48 was instantiated in the design, it is suggested to set both the MREG and PREG attributes to 1 when performing multiply functions.}}  -suppress 
set_msg_config  -ruleid {158}  -id {Synth 8-6157}  -string {{INFO: [Synth 8-6157] synthesizing module 'zedboard_base_axi_smc_0' [/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/synth_1/.Xil/Vivado-11605-tingyuan-OptiPlex-9010/realtime/zedboard_base_axi_smc_0_stub.v:6]}}  -suppress 
set_msg_config  -ruleid {159}  -id {Synth 8-6155}  -string {{INFO: [Synth 8-6155] done synthesizing module 'm00_couplers_imp_AAU18Z' (3#1) [/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/synth/zedboard_base.v:12]}}  -suppress 
set_msg_config  -ruleid {160}  -id {Synth 8-350}  -string {{WARNING: [Synth 8-350] instance 'rst_ps7_0_200M' of module 'zedboard_base_rst_ps7_0_200M_0' requires 10 connections, but only 7 given [/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/synth/zedboard_base.v:1311]}}  -suppress 
set_msg_config  -ruleid {161}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_1GT4T1J has unconnected port M_ACLK}}  -suppress 
set_msg_config  -ruleid {163}  -id {Synth 8-6157}  -string {{INFO: [Synth 8-6157] synthesizing module 'BUFG' [/opt/Xilinx_201802/Vivado/2018.2/scripts/rt/data/unisim_comp.v:609]}}  -suppress 
set_msg_config  -ruleid {164}  -id {Synth 8-6155}  -string {{INFO: [Synth 8-6155] done synthesizing module 'PS7' (3#1) [/opt/Xilinx_201802/Vivado/2018.2/scripts/rt/data/unisim_comp.v:40565]}}  -suppress 
set_msg_config  -ruleid {165}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design processing_system7_v5_5_processing_system7 has unconnected port ENET0_GMII_RX_DV}}  -suppress 
set_msg_config  -ruleid {166}  -string {{Attempting to get a license for feature 'Synthesis' and/or device 'xc7z020'}}  -suppress 
set_msg_config  -ruleid {167}  -id {IP_Flow 19-1700}  -string {{INFO: [IP_Flow 19-1700] Loaded user IP repository '/home/tingyuan/VerilogPrj'.}}  -suppress 
set_msg_config  -ruleid {168}  -id {Project 1-454}  -string {{INFO: [Project 1-454] Reading design checkpoint '/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps7_0_200M_0/zedboard_base_rst_ps7_0_200M_0.dcp' for cell 'zedboard_base_i/rst_ps7_0_200M'}}  -suppress 
set_msg_config  -ruleid {169}  -string {{Design is defaulting to constrset: constrs_1}}  -suppress 
set_msg_config  -ruleid {170}  -string {{Running DRC as a precondition to command opt_design}}  -suppress 
set_msg_config  -ruleid {171}  -id {Opt 31-389}  -string {{INFO: [Opt 31-389] Phase Sweep created 0 cells and removed 3839 cells}}  -suppress 
set_msg_config  -ruleid {172}  -string {{Running DRC as a precondition to command place_design}}  -suppress 
set_msg_config  -ruleid {173}  -id {runtcl-4}  -string {{INFO: [runtcl-4] Executing : report_control_sets -verbose -file zedboard_base_wrapper_control_sets_placed.rpt}}  -suppress 
set_msg_config  -ruleid {174}  -string {{Running DRC as a precondition to command route_design}}  -suppress 
set_msg_config  -ruleid {175}  -id {Route 35-416}  -string {{INFO: [Route 35-416] Intermediate Timing Summary | WNS=-0.880 | TNS=-29.620| WHS=N/A    | THS=N/A    |}}  -suppress 
set_msg_config  -ruleid {176}  -id {runtcl-4}  -string {{INFO: [runtcl-4] Executing : report_power -file zedboard_base_wrapper_power_routed.rpt -pb zedboard_base_wrapper_power_summary_routed.pb -rpx zedboard_base_wrapper_power_routed.rpx}}  -suppress 
set_msg_config  -ruleid {177}  -id {Memdata 28-167}  -string {{INFO: [Memdata 28-167] Found XPM memory block zedboard_base_i/axi_smc/inst/s04_nodes/s04_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory/xpm_memory_base_inst with a P_MEMORY_PRIMITIVE property set to distributed. A value of block is required. You will not be able to use the updatemem program to update the bitstream with new data for the zedboard_base_i/axi_smc/inst/s04_nodes/s04_r_node/inst/inst_mi_handler/gen_normal_area.inst_fifo_node_payld/gen_xpm_memory_fifo.inst_fifo/gen_mem_rep[0].inst_xpm_memory/xpm_memory_base_inst block.}}  -suppress 
set_msg_config  -ruleid {178}  -id {DRC DPOP-2}  -string {{WARNING: [DRC DPOP-2] MREG Output pipelining: DSP zedboard_base_i/zedboard_base_kernel_0/inst/inst/kernel_2mm_U0/func15_U0/grp_func1_execute8_fu_66/kernel_2mm_wrappecud_U47/kernel_2mm_wrappecud_MulnS_1_U/buff0_reg multiplier stage zedboard_base_i/zedboard_base_kernel_0/inst/inst/kernel_2mm_U0/func15_U0/grp_func1_execute8_fu_66/kernel_2mm_wrappecud_U47/kernel_2mm_wrappecud_MulnS_1_U/buff0_reg/P[47:0] is not pipelined (MREG=0). Pipelining the multiplier function will improve performance and will save significant power so it is suggested whenever possible to fully pipeline this function.  If this multiplier was inferred, it is suggested to describe an additional register stage after this function.  If there is no registered adder/accumulator following the multiply function, two pipeline stages are suggested to allow both the MREG and PREG registers to be used.  If the DSP48 was instantiated in the design, it is suggested to set both the MREG and PREG attributes to 1 when performing multiply functions.}}  -suppress 
set_msg_config  -ruleid {179}  -string {{Running DRC as a precondition to command write_bitstream}}  -suppress 
set_msg_config  -ruleid {21}  -id {Common 17-1381}  -string {{INFO: [Common 17-1381] The checkpoint '/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/synth_1/zedboard_base_wrapper.dcp' has been generated.}}  -suppress 
set_msg_config  -ruleid {22}  -id {runtcl-4}  -string {{INFO: [runtcl-4] Executing : report_utilization -file zedboard_base_wrapper_utilization_synth.rpt -pb zedboard_base_wrapper_utilization_synth.pb}}  -suppress 
set_msg_config  -ruleid {23}  -id {Common 17-206}  -string {{INFO: [Common 17-206] Exiting Vivado at Fri Sep  6 14:11:07 2019...}}  -suppress 
set_msg_config  -ruleid {24}  -string {{Command: synth_design -top zedboard_base_processing_system7_0_0 -part xc7z020clg484-1 -mode out_of_context}}  -suppress 
set_msg_config  -ruleid {25}  -id {Common 17-349}  -string {{INFO: [Common 17-349] Got license for feature 'Synthesis' and/or device 'xc7z020'}}  -suppress 
set_msg_config  -ruleid {26}  -id {Synth 8-6157}  -string {{INFO: [Synth 8-6157] synthesizing module 'zedboard_base_processing_system7_0_0' [/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_processing_system7_0_0/synth/zedboard_base_processing_system7_0_0.v:60]}}  -suppress 
set_msg_config  -ruleid {27}  -id {Synth 8-5534}  -string {{INFO: [Synth 8-5534] Detected attribute (* keep = "true" *) [/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v:1348]}}  -suppress 
set_msg_config  -ruleid {28}  -id {Synth 8-6155}  -string {{INFO: [Synth 8-6155] done synthesizing module 'BUFG' (1#1) [/opt/Xilinx_201802/Vivado/2018.2/scripts/rt/data/unisim_comp.v:609]}}  -suppress 
set_msg_config  -ruleid {29}  -id {Synth 8-350}  -string {{WARNING: [Synth 8-350] instance 'inst' of module 'processing_system7_v5_5_processing_system7' requires 685 connections, but only 672 given [/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_processing_system7_0_0/synth/zedboard_base_processing_system7_0_0.v:475]}}  -suppress 
set_msg_config  -ruleid {30}  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design processing_system7_v5_5_processing_system7 has unconnected port ENET0_GMII_COL}}  -suppress 
set_msg_config  -ruleid {32}  -id {Project 1-236}  -string {{INFO: [Project 1-236] Implementation specific constraints were found while reading constraint file [/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_processing_system7_0_0/zedboard_base_processing_system7_0_0.xdc]. These constraints will be ignored for synthesis but will be used in implementation. Impacted constraints are listed in the file [.Xil/zedboard_base_processing_system7_0_0_propImpl.xdc].
Resolution: To avoid this warning, move constraints listed in ['Undefined'] to another XDC file and exclude this new file from synthesis with the used_in_synthesis property (File Properties dialog in GUI) and re-run elaboration/synthesis.}}  -suppress 
set_msg_config  -ruleid {33}  -id {Common 17-14}  -string {{INFO: [Common 17-14] Message 'Synth 8-3331' appears 100 times and further instances of the messages will be disabled. Use the Tcl command set_msg_config to change the current settings.}}  -suppress 
set_msg_config  -ruleid {34}  -id {Project 1-571}  -string {{INFO: [Project 1-571] Translating synthesized netlist}}  -suppress 
set_msg_config  -ruleid {37}  -id {Project 1-111}  -string {{INFO: [Project 1-111] Unisim Transformation Summary:
No Unisim elements were transformed.}}  -suppress 
set_msg_config  -ruleid {38}  -id {Common 17-83}  -string {{INFO: [Common 17-83] Releasing license: Synthesis}}  -suppress 
set_msg_config  -ruleid {39}  -id {Coretcl 2-1482}  -string {{INFO: [Coretcl 2-1482] Added synthesis output to IP cache for IP /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_processing_system7_0_0/zedboard_base_processing_system7_0_0.xci}}  -suppress 
set_msg_config  -ruleid {40}  -id {Constraints 18-5210}  -string {{WARNING: [Constraints 18-5210] No constraint will be written out.}}  -suppress 
set_msg_config  -ruleid {41}  -id {Common 17-1381}  -string {{INFO: [Common 17-1381] The checkpoint '/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/zedboard_base_processing_system7_0_0_synth_1/zedboard_base_processing_system7_0_0.dcp' has been generated.}}  -suppress 
set_msg_config  -ruleid {42}  -id {runtcl-4}  -string {{INFO: [runtcl-4] Executing : report_utilization -file zedboard_base_processing_system7_0_0_utilization_synth.rpt -pb zedboard_base_processing_system7_0_0_utilization_synth.pb}}  -suppress 
set_msg_config  -ruleid {43}  -id {Common 17-206}  -string {{INFO: [Common 17-206] Exiting Vivado at Fri Sep  6 16:26:05 2019...}}  -suppress 
set_msg_config  -ruleid {44}  -id {IP_Flow 19-234}  -string {{INFO: [IP_Flow 19-234] Refreshing IP repositories}}  -suppress 
set_msg_config  -ruleid {45}  -id {IP_Flow 19-3685}  -string {{WARNING: [IP_Flow 19-3685] Ignored loading user repository '/home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.ipdefs/vivado-outputs_0'. The path is contained within another repository.}}  -suppress 
set_msg_config  -ruleid {46}  -id {IP_Flow 19-1700}  -string {{INFO: [IP_Flow 19-1700] Loaded user IP repository '/home/tingyuan/Documents/ddr_check'.}}  -suppress 
set_msg_config  -ruleid {47}  -id {IP_Flow 19-2313}  -string {{INFO: [IP_Flow 19-2313] Loaded Vivado IP repository '/opt/Xilinx_201802/Vivado/2018.2/data/ip'.}}  -suppress 
set_msg_config  -ruleid {48}  -id {IP_Flow 19-1663}  -string {{CRITICAL WARNING: [IP_Flow 19-1663] Duplicate IP found for 'user.org:user:kernel_2mm_wrapper_multiClock:1.2'. The one found in IP location '/home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.tmp/kernel_2mm_wrapper_multiClock_v1_2_project/kernel_2mm_wrapper_multiClock_v1_2_project.srcs/sources_1/imports/ip_source' will take precedence over the same IP in location /home/tingyuan/Dropbox/Hi-ClockFLow_Benchmarks/2mm/tmp}}  -suppress 
set_msg_config  -ruleid {49}  -string {{Command: link_design -top zedboard_base_wrapper -part xc7z020clg484-1}}  -suppress 
set_msg_config  -ruleid {50}  -id {Project 1-454}  -string {{INFO: [Project 1-454] Reading design checkpoint '/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/zedboard_base_axi_smc_0.dcp' for cell 'zedboard_base_i/axi_smc'}}  -suppress 
set_msg_config  -ruleid {51}  -id {Netlist 29-17}  -string {{INFO: [Netlist 29-17] Analyzing 1377 Unisim elements for replacement}}  -suppress 
set_msg_config  -ruleid {52}  -id {Netlist 29-28}  -string {{INFO: [Netlist 29-28] Unisim Transformation completed in 0 CPU seconds}}  -suppress 
set_msg_config  -ruleid {53}  -id {Project 1-479}  -string {{INFO: [Project 1-479] Netlist was created with Vivado 2018.2}}  -suppress 
set_msg_config  -ruleid {54}  -id {Device 21-403}  -string {{INFO: [Device 21-403] Loading part xc7z020clg484-1}}  -suppress 
set_msg_config  -ruleid {55}  -id {Project 1-570}  -string {{INFO: [Project 1-570] Preparing netlist for logic optimization}}  -suppress 
set_msg_config  -ruleid {57}  -id {Project 1-111}  -string {{INFO: [Project 1-111] Unisim Transformation Summary:
  A total of 614 instances were transformed.
  RAM16X1D => RAM32X1D (RAMD32, RAMD32): 5 instances
  RAM32M => RAM32M (RAMD32, RAMD32, RAMD32, RAMD32, RAMD32, RAMD32, RAMS32, RAMS32): 596 instances
  RAM32X1D => RAM32X1D (RAMD32, RAMD32): 13 instances}}  -suppress 
set_msg_config  -ruleid {58}  -string {{Command: opt_design}}  -suppress 
set_msg_config  -ruleid {6}  -string {{Command: synth_design -top zedboard_base_wrapper -part xc7z020clg484-1}}  -suppress 
set_msg_config  -ruleid {60}  -id {Project 1-461}  -string {{INFO: [Project 1-461] DRC finished with 0 Errors}}  -suppress 
set_msg_config  -ruleid {61}  -id {Project 1-462}  -string {{INFO: [Project 1-462] Please refer to the DRC report (report_drc) for more information.}}  -suppress 
set_msg_config  -ruleid {62}  -id {Opt 31-49}  -string {{INFO: [Opt 31-49] Retargeted 0 cell(s).}}  -suppress 
set_msg_config  -ruleid {63}  -id {Opt 31-138}  -string {{INFO: [Opt 31-138] Pushed 40 inverter(s) to 128 load pin(s).}}  -suppress 
set_msg_config  -ruleid {64}  -id {Opt 31-389}  -string {{INFO: [Opt 31-389] Phase Retarget created 0 cells and removed 0 cells}}  -suppress 
set_msg_config  -ruleid {65}  -id {Opt 31-662}  -string {{INFO: [Opt 31-662] Phase BUFG optimization created 0 cells of which 0 are BUFGs and removed 0 cells.}}  -suppress 
set_msg_config  -ruleid {66}  -id {Pwropt 34-132}  -string {{INFO: [Pwropt 34-132] Skipping clock gating for clocks with a period < 2.00 ns.}}  -suppress 
set_msg_config  -ruleid {68}  -id {Pwropt 34-9}  -string {{INFO: [Pwropt 34-9] Applying IDT optimizations ...}}  -suppress 
set_msg_config  -ruleid {69}  -id {Pwropt 34-10}  -string {{INFO: [Pwropt 34-10] Applying ODC optimizations ...}}  -suppress 
set_msg_config  -ruleid {70}  -id {Physopt 32-619}  -string {{INFO: [Physopt 32-619] Estimated Timing Summary | WNS=-1.917 | TNS=-69.538 |}}  -suppress 
set_msg_config  -ruleid {71}  -id {Pwropt 34-162}  -string {{INFO: [Pwropt 34-162] WRITE_MODE attribute of 3 BRAM(s) out of a total of 36 has been updated to save power. Run report_power_opt to get a complete listing of the BRAMs updated.}}  -suppress 
set_msg_config  -ruleid {72}  -id {Pwropt 34-201}  -string {{INFO: [Pwropt 34-201] Structural ODC has moved 2 WE to EN ports}}  -suppress 
set_msg_config  -ruleid {75}  -id {Common 17-1381}  -string {{INFO: [Common 17-1381] The checkpoint '/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/impl_1/zedboard_base_wrapper_opt.dcp' has been generated.}}  -suppress 
set_msg_config  -ruleid {76}  -id {runtcl-4}  -string {{INFO: [runtcl-4] Executing : report_drc -file zedboard_base_wrapper_drc_opted.rpt -pb zedboard_base_wrapper_drc_opted.pb -rpx zedboard_base_wrapper_drc_opted.rpx}}  -suppress 
set_msg_config  -ruleid {78}  -id {Coretcl 2-168}  -string {{INFO: [Coretcl 2-168] The results of DRC are in file /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/impl_1/zedboard_base_wrapper_drc_opted.rpt.}}  -suppress 
set_msg_config  -ruleid {79}  -string {{Command: place_design}}  -suppress 
set_msg_config  -ruleid {8}  -id {Synth 8-6157}  -string {{INFO: [Synth 8-6157] synthesizing module 'zedboard_base_wrapper' [/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/hdl/zedboard_base_wrapper.v:12]}}  -suppress 
set_msg_config  -ruleid {84}  -id {Place 30-611}  -string {{INFO: [Place 30-611] Multithreading enabled for place_design using a maximum of 4 CPUs}}  -suppress 
set_msg_config  -ruleid {85}  -id {Opt 31-138}  -string {{INFO: [Opt 31-138] Pushed 0 inverter(s) to 0 load pin(s).}}  -suppress 
set_msg_config  -ruleid {87}  -id {Physopt 32-65}  -string {{INFO: [Physopt 32-65] No nets found for high-fanout optimization.}}  -suppress 
set_msg_config  -ruleid {88}  -id {Physopt 32-64}  -string {{INFO: [Physopt 32-64] No nets found for fanout-optimization.}}  -suppress 
set_msg_config  -ruleid {89}  -id {Physopt 32-232}  -string {{INFO: [Physopt 32-232] Optimized 0 net. Created 0 new instance.}}  -suppress 
set_msg_config  -ruleid {9}  -id {Synth 8-6155}  -string {{INFO: [Synth 8-6155] done synthesizing module 'zedboard_base_axi_smc_0' (1#1) [/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/synth_1/.Xil/Vivado-11605-tingyuan-OptiPlex-9010/realtime/zedboard_base_axi_smc_0_stub.v:6]}}  -suppress 
set_msg_config  -ruleid {90}  -id {Physopt 32-775}  -string {{INFO: [Physopt 32-775] End 1 Pass. Optimized 0 net or cell. Created 0 new cell, deleted 0 existing cell and moved 0 existing cell}}  -suppress 
set_msg_config  -ruleid {91}  -id {Place 46-33}  -string {{INFO: [Place 46-33] Processed net zedboard_base_i/zedboard_base_kernel_0/inst/inst/kernel_2mm_wrapper_gmem4_m_axi_U/bus_write/buff_wdata/q_tmp_reg[0]_0, BUFG insertion was skipped due to placement/routing conflicts.}}  -suppress 
set_msg_config  -ruleid {92}  -id {Place 46-31}  -string {{INFO: [Place 46-31] BUFG insertion identified 1 candidate nets, 0 success, 1 skipped for placement/routing, 0 skipped for timing, 0 skipped for netlist change reason.}}  -suppress 
set_msg_config  -ruleid {93}  -id {Place 30-746}  -string {{INFO: [Place 30-746] Post Placement Timing Summary WNS=-0.234. For the most accurate timing information please run report_timing.}}  -suppress 
set_msg_config  -ruleid {96}  -id {Common 17-1381}  -string {{INFO: [Common 17-1381] The checkpoint '/home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/impl_1/zedboard_base_wrapper_placed.dcp' has been generated.}}  -suppress 
set_msg_config  -ruleid {97}  -id {runtcl-4}  -string {{INFO: [runtcl-4] Executing : report_io -file zedboard_base_wrapper_io_placed.rpt}}  -suppress 
set_msg_config  -ruleid {98}  -string {{Command: route_design}}  -suppress 
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.cache/wt [current_project]
set_property parent.project_path /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.ipdefs/vivado-outputs_0
  /home/tingyuan/Documents/ddr_check
  /home/tingyuan/Dropbox/Hi-ClockFLow_Benchmarks
  /home/tingyuan/VerilogPrj
  /home/tingyuan/Documents/VivadoPrj_backup/2mm_freqChange
} [current_project]
set_property ip_output_repo /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_xbar_0/zedboard_base_xbar_0.xci
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_xbar_0/zedboard_base_xbar_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/zedboard_base_xbar_0_synth_1 -new_name zedboard_base_xbar_0 -ip [get_ips zedboard_base_xbar_0]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top zedboard_base_xbar_0 -part xc7z020clg484-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix zedboard_base_xbar_0_ zedboard_base_xbar_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ zedboard_base_xbar_0_stub.v
 lappend ipCachedFiles zedboard_base_xbar_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ zedboard_base_xbar_0_stub.vhdl
 lappend ipCachedFiles zedboard_base_xbar_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ zedboard_base_xbar_0_sim_netlist.v
 lappend ipCachedFiles zedboard_base_xbar_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ zedboard_base_xbar_0_sim_netlist.vhdl
 lappend ipCachedFiles zedboard_base_xbar_0_sim_netlist.vhdl
set TIME_taken [expr [clock seconds] - $TIME_start]

 config_ip_cache -add -dcp zedboard_base_xbar_0.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips zedboard_base_xbar_0]
}

rename_ref -prefix_all zedboard_base_xbar_0_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zedboard_base_xbar_0.dcp
create_report "zedboard_base_xbar_0_synth_1_synth_report_utilization_0" "report_utilization -file zedboard_base_xbar_0_utilization_synth.rpt -pb zedboard_base_xbar_0_utilization_synth.pb"

if { [catch {
  file copy -force /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/zedboard_base_xbar_0_synth_1/zedboard_base_xbar_0.dcp /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_xbar_0/zedboard_base_xbar_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_xbar_0/zedboard_base_xbar_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_xbar_0/zedboard_base_xbar_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_xbar_0/zedboard_base_xbar_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_xbar_0/zedboard_base_xbar_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/zedboard_base_xbar_0_synth_1/zedboard_base_xbar_0.dcp /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_xbar_0/zedboard_base_xbar_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/zedboard_base_xbar_0_synth_1/zedboard_base_xbar_0_stub.v /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_xbar_0/zedboard_base_xbar_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/zedboard_base_xbar_0_synth_1/zedboard_base_xbar_0_stub.vhdl /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_xbar_0/zedboard_base_xbar_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/zedboard_base_xbar_0_synth_1/zedboard_base_xbar_0_sim_netlist.v /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_xbar_0/zedboard_base_xbar_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.runs/zedboard_base_xbar_0_synth_1/zedboard_base_xbar_0_sim_netlist.vhdl /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_xbar_0/zedboard_base_xbar_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.ip_user_files/ip/zedboard_base_xbar_0]} {
  catch { 
    file copy -force /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_xbar_0/zedboard_base_xbar_0_stub.v /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.ip_user_files/ip/zedboard_base_xbar_0
  }
}

if {[file isdir /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.ip_user_files/ip/zedboard_base_xbar_0]} {
  catch { 
    file copy -force /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_xbar_0/zedboard_base_xbar_0_stub.vhdl /home/tingyuan/Documents/VivadoPrj_backup/HLSExtractedIntoIP_0905/HLSExtractedIntoIP/HLSExtractedIntoIP.ip_user_files/ip/zedboard_base_xbar_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
