# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.cache/wt [current_project]
set_property parent.project_path /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.ipdefs/vivado-outputs_0
  /home/tingyuan/Documents/ddr_check
  /home/tingyuan/Dropbox/Hi-ClockFLow_Benchmarks
  /home/tingyuan/VerilogPrj
  /home/tingyuan/Documents/VivadoPrj_backup/2mm_freqChange
} [current_project]
set_property ip_output_repo /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/hdl/zedboard_base_wrapper.v
add_files /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/zedboard_base.bd
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_processing_system7_0_0/zedboard_base_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_timer_0_0/constraints/timer_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_12/bd_777a_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_21/bd_777a_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_30/bd_777a_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_39/bd_777a_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_48/bd_777a_s04a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_57/bd_777a_s05a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_66/bd_777a_s06a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_75/bd_777a_s07a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_84/bd_777a_s08a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_93/bd_777a_s09a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_99/bd_777a_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_100/bd_777a_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_101/bd_777a_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_102/bd_777a_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_103/bd_777a_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_104/bd_777a_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_94/bd_777a_sarn_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_95/bd_777a_srn_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_96/bd_777a_sawn_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_97/bd_777a_swn_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_98/bd_777a_sbn_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_85/bd_777a_sarn_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_86/bd_777a_srn_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_87/bd_777a_sawn_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_88/bd_777a_swn_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_89/bd_777a_sbn_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_76/bd_777a_sarn_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_77/bd_777a_srn_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_78/bd_777a_sawn_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_79/bd_777a_swn_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_80/bd_777a_sbn_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_67/bd_777a_sarn_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_68/bd_777a_srn_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_69/bd_777a_sawn_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_70/bd_777a_swn_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_71/bd_777a_sbn_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_58/bd_777a_sarn_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_59/bd_777a_srn_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_60/bd_777a_sawn_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_61/bd_777a_swn_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_62/bd_777a_sbn_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_49/bd_777a_sarn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_50/bd_777a_srn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_51/bd_777a_sawn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_52/bd_777a_swn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_53/bd_777a_sbn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_40/bd_777a_sarn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_41/bd_777a_srn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_42/bd_777a_sawn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_43/bd_777a_swn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_44/bd_777a_sbn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_31/bd_777a_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_32/bd_777a_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_33/bd_777a_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_34/bd_777a_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_35/bd_777a_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_22/bd_777a_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_23/bd_777a_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_24/bd_777a_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_25/bd_777a_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_26/bd_777a_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_13/bd_777a_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_14/bd_777a_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_15/bd_777a_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_16/bd_777a_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_17/bd_777a_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_4/bd_777a_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_5/bd_777a_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_6/bd_777a_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_7/bd_777a_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_8/bd_777a_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_1/bd_777a_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_1/bd_777a_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_2/bd_777a_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_2/bd_777a_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_3/bd_777a_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_3/bd_777a_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps7_0_100M_0/zedboard_base_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps7_0_100M_0/zedboard_base_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps7_0_100M_0/zedboard_base_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps7_0_200M_1/zedboard_base_rst_ps7_0_200M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps7_0_200M_1/zedboard_base_rst_ps7_0_200M_1.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps7_0_200M_1/zedboard_base_rst_ps7_0_200M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_xbar_0/zedboard_base_xbar_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_auto_cc_1/zedboard_base_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_auto_cc_1/zedboard_base_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_auto_cc_1/zedboard_base_auto_cc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_auto_cc_0/zedboard_base_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_auto_cc_0/zedboard_base_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_auto_cc_0/zedboard_base_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_auto_pc_0/zedboard_base_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/tingyuan/Documents/VivadoPrj_backup/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907/HLSMultiIPDiffClock_0907.srcs/sources_1/bd/zedboard_base/zedboard_base_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top zedboard_base_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zedboard_base_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file zedboard_base_wrapper_utilization_synth.rpt -pb zedboard_base_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
