// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================
#include "xstatus.h"
#include "xparameters.h"
#include "xclockChange.h"

/*
* The configuration table for devices
*/

Zynq_2mm_clockChange_Config Zynq_2mm_clockChange_ConfigTable[XPAR_ZYNQ_2MM_CLOCKCHANGE_NUM_INSTANCES] =
{
	{
			XPAR_ZYNQ_2MM_CLOCKCHANGE_0_DEVICE_ID,
		XPAR_ZYNQ_2MM_CLOCKCHANGE_0_S_AXI_BUS_A_BASEADDR
	},
	{
			XPAR_ZYNQ_2MM_CLOCKCHANGE_1_DEVICE_ID,
		XPAR_ZYNQ_2MM_CLOCKCHANGE_1_S_AXI_BUS_A_BASEADDR
	}
};




Zynq_2mm_clockChange_Config *Zynq_2mm_clockChange_LookupConfig(u16 DeviceId) {
	Zynq_2mm_clockChange_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_ZYNQ_2MM_CLOCKCHANGE_NUM_INSTANCES; Index++) {
		if (Zynq_2mm_clockChange_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &Zynq_2mm_clockChange_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int Zynq_2mm_clockChange_Initialize(Zynq_2mm_clockChange *InstancePtr, u16 DeviceId) {
	Zynq_2mm_clockChange_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = Zynq_2mm_clockChange_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return Zynq_2mm_clockChange_CfgInitialize(InstancePtr, ConfigPtr);
}

