// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xclockChange.h"

/************************** Function Implementation *************************/

int Zynq_2mm_clockChange_CfgInitialize(Zynq_2mm_clockChange *InstancePtr, Zynq_2mm_clockChange_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->For_control_BaseAddress = ConfigPtr->For_control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}

void Zynq_2mm_clockChange_Start(Zynq_2mm_clockChange *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = Zynq_2mm_clockChange_ReadReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_AP_CTRL) & 0x80;
    Zynq_2mm_clockChange_WriteReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 Zynq_2mm_clockChange_IsDone(Zynq_2mm_clockChange *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = Zynq_2mm_clockChange_ReadReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 Zynq_2mm_clockChange_IsIdle(Zynq_2mm_clockChange *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = Zynq_2mm_clockChange_ReadReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 Zynq_2mm_clockChange_IsReady(Zynq_2mm_clockChange *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = Zynq_2mm_clockChange_ReadReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void Zynq_2mm_clockChange_EnableAutoRestart(Zynq_2mm_clockChange *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Zynq_2mm_clockChange_WriteReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_AP_CTRL, 0x80);
}

void Zynq_2mm_clockChange_DisableAutoRestart(Zynq_2mm_clockChange *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Zynq_2mm_clockChange_WriteReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_AP_CTRL, 0);
}

void Zynq_2mm_clockChange_Set_A_AXI(Zynq_2mm_clockChange *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Zynq_2mm_clockChange_WriteReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_A_AXI_DATA, Data);
}

u32 Zynq_2mm_clockChange_Get_A_AXI(Zynq_2mm_clockChange *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = Zynq_2mm_clockChange_ReadReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_A_AXI_DATA);
    return Data;
}

void Zynq_2mm_clockChange_Set_B_AXI(Zynq_2mm_clockChange *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Zynq_2mm_clockChange_WriteReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_B_AXI_DATA, Data);
}

u32 Zynq_2mm_clockChange_Get_B_AXI(Zynq_2mm_clockChange *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = Zynq_2mm_clockChange_ReadReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_B_AXI_DATA);
    return Data;
}

void Zynq_2mm_clockChange_Set_C_AXI(Zynq_2mm_clockChange *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Zynq_2mm_clockChange_WriteReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_C_AXI_DATA, Data);
}

u32 Zynq_2mm_clockChange_Get_C_AXI(Zynq_2mm_clockChange *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = Zynq_2mm_clockChange_ReadReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_C_AXI_DATA);
    return Data;
}

void Zynq_2mm_clockChange_Set_D_input_AXI(Zynq_2mm_clockChange *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Zynq_2mm_clockChange_WriteReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_D_INPUT_AXI_DATA, Data);
}

u32 Zynq_2mm_clockChange_Get_D_input_AXI(Zynq_2mm_clockChange *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = Zynq_2mm_clockChange_ReadReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_D_INPUT_AXI_DATA);
    return Data;
}

void Zynq_2mm_clockChange_Set_D_output_AXI(Zynq_2mm_clockChange *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Zynq_2mm_clockChange_WriteReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_D_OUTPUT_AXI_DATA, Data);
}

u32 Zynq_2mm_clockChange_Get_D_output_AXI(Zynq_2mm_clockChange *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = Zynq_2mm_clockChange_ReadReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_D_OUTPUT_AXI_DATA);
    return Data;
}

void Zynq_2mm_clockChange_InterruptGlobalEnable(Zynq_2mm_clockChange *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Zynq_2mm_clockChange_WriteReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_GIE, 1);
}

void Zynq_2mm_clockChange_InterruptGlobalDisable(Zynq_2mm_clockChange *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Zynq_2mm_clockChange_WriteReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_GIE, 0);
}

void Zynq_2mm_clockChange_InterruptEnable(Zynq_2mm_clockChange *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  Zynq_2mm_clockChange_ReadReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_IER);
    Zynq_2mm_clockChange_WriteReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_IER, Register | Mask);
}

void Zynq_2mm_clockChange_InterruptDisable(Zynq_2mm_clockChange *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  Zynq_2mm_clockChange_ReadReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_IER);
    Zynq_2mm_clockChange_WriteReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_IER, Register & (~Mask));
}

void Zynq_2mm_clockChange_InterruptClear(Zynq_2mm_clockChange *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Zynq_2mm_clockChange_WriteReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_ISR, Mask);
}

u32 Zynq_2mm_clockChange_InterruptGetEnabled(Zynq_2mm_clockChange *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return Zynq_2mm_clockChange_ReadReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_IER);
}

u32 Zynq_2mm_clockChange_InterruptGetStatus(Zynq_2mm_clockChange *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return Zynq_2mm_clockChange_ReadReg(InstancePtr->For_control_BaseAddress, ZYNQ_2MM_CLOCKCHANGE_FOR_CONTROL_ADDR_ISR);
}

